# Generated by Django 5.2.15 on 2026-09-14 19:43

import django.db.models.deletion
import memz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptionDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[("he", "עברית"), ("en", "English")], default="he", max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memz_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CaptionCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=140)),
                ("order", models.IntegerField(default=0)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="memz.captiondeck",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MemeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.ImageField(upload_to="memz/images/%Y/%m/")),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "public"), ("private", "private")],
                        default="private",
                        max_length=8,
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("moderation_note", models.TextField(blank=True)),
                ("seed_key", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memz_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("caption_text", models.TextField()),
                ("rendered", models.ImageField(upload_to="memz/memes/%Y/%m/")),
                (
                    "source",
                    models.CharField(
                        choices=[("game", "game"), ("solo", "solo")], default="solo", max_length=4
                    ),
                ),
                (
                    "share_slug",
                    models.CharField(
                        default=memz.models.new_share_slug, max_length=32, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "caption_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memes",
                        to="memz.captioncard",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memz_memes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memes",
                        to="memz.memeimage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MemzProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "free"), ("paid", "paid")], default="free", max_length=8
                    ),
                ),
                ("display_name", models.CharField(max_length=40)),
                ("paid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memz_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(allow_unicode=True, max_length=80)),
                ("is_public", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memz_packs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_links",
                        to="memz.memeimage",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="memz.pack",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="pack",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="packs", through="memz.PackImage", to="memz.memeimage"
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nickname", models.CharField(max_length=16)),
                (
                    "guest_token",
                    models.CharField(default=memz.models.new_token, max_length=64, unique=True),
                ),
                ("is_host", models.BooleanField(default=False)),
                ("seat_order", models.PositiveSmallIntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memz_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seat_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HandCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dealt_in_round", models.PositiveSmallIntegerField()),
                ("played_in_round", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_hands",
                        to="memz.captioncard",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand",
                        to="memz.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedMeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="memz.meme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memz_saved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "lobby"),
                            ("playing", "playing"),
                            ("finished", "finished"),
                            ("abandoned", "abandoned"),
                        ],
                        default="lobby",
                        max_length=10,
                    ),
                ),
                (
                    "game_mode",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("topics", "topics"),
                            ("same_meme", "same_meme"),
                            ("relaxed", "relaxed"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "caption_mode",
                    models.CharField(
                        choices=[("typed", "typed"), ("cards", "cards")],
                        default="typed",
                        max_length=6,
                    ),
                ),
                (
                    "scoring_mode",
                    models.CharField(
                        choices=[("vote", "vote"), ("judge", "judge")], default="vote", max_length=6
                    ),
                ),
                (
                    "image_source",
                    models.CharField(
                        choices=[
                            ("public_random", "public_random"),
                            ("packs", "packs"),
                            ("own_only", "own_only"),
                            ("mix", "mix"),
                        ],
                        default="public_random",
                        max_length=14,
                    ),
                ),
                ("round_count", models.PositiveSmallIntegerField(default=5)),
                ("round_seconds", models.PositiveSmallIntegerField(default=60)),
                ("vote_seconds", models.PositiveSmallIntegerField(default=20)),
                ("max_players", models.PositiveSmallIntegerField(default=5)),
                ("remembered", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="memz.captiondeck",
                    ),
                ),
                (
                    "host_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memz_hosted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "packs",
                    models.ManyToManyField(blank=True, related_name="sessions", to="memz.pack"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("captioning", "captioning"),
                            ("voting", "voting"),
                            ("revealed", "revealed"),
                            ("done", "done"),
                        ],
                        default="captioning",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("caption_deadline", models.DateTimeField(blank=True, null=True)),
                ("vote_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "judge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judged_rounds",
                        to="memz.player",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="memz.session",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="memz.session",
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealt_in",
                        to="memz.memeimage",
                    ),
                ),
                (
                    "meme",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission",
                        to="memz.meme",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="memz.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="memz.round",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=80)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[("he", "עברית"), ("en", "English")], default="he", max_length=2
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memz_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["text"],
            },
        ),
        migrations.AddField(
            model_name="round",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rounds",
                to="memz.topic",
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="memz.round",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="memz.submission",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_cast",
                        to="memz.player",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="memeimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seed_key", ""), _negated=True),
                fields=("seed_key",),
                name="memz_image_seed_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="packimage",
            constraint=models.UniqueConstraint(
                fields=("pack", "image"), name="memz_pack_image_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="memz_pack_owner_slug_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("slug",),
                name="memz_public_pack_slug_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedmeme",
            constraint=models.UniqueConstraint(
                fields=("user", "meme"), name="memz_saved_once_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("lobby", "playing"))),
                fields=("code",),
                name="memz_session_code_active_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("session", "nickname"), name="memz_player_nickname_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("round", "player"), name="memz_submission_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("session", "number"), name="memz_round_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("round", "voter"), name="memz_vote_once_per_round"
            ),
        ),
    ]
