# Generated by Django 5.2.15 on 2026-09-15 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="carried_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carried_to",
                to="memz.player",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="reveal_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="next_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_session",
                to="memz.session",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
