# Generated by Django 5.2.15 on 2026-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0002_player_carried_from_round_reveal_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="card_swap_used",
            field=models.BooleanField(default=False),
        ),
    ]
