# Generated by Django 5.2.15 on 2026-09-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0003_player_card_swap_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_ai",
            field=models.BooleanField(default=False),
        ),
    ]
