# Generated by Django 5.2.15 on 2026-09-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0004_player_is_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="source_credit",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
