# Generated by Django 5.2.15 on 2026-09-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0005_meme_source_credit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="memz_vote_once_per_round",
        ),
        migrations.AddField(
            model_name="submission",
            name="image_swaps_used",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vote",
            name="value",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "אוהב"), (1, "ככה ככה"), (0, "פחות")], default=2
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("round", "voter", "submission"), name="memz_vote_once_per_meme"
            ),
        ),
    ]
