# Generated by Django 5.2.15 on 2026-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0006_remove_vote_memz_vote_once_per_round_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="swapped_away_image_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
