# Generated by Django 5.2.15 on 2026-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0007_submission_swapped_away_image_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="image_source",
            field=models.CharField(
                choices=[
                    ("public_random", "public_random"),
                    ("packs", "packs"),
                    ("own_only", "own_only"),
                    ("mix", "mix"),
                ],
                default="mix",
                max_length=14,
            ),
        ),
    ]
