# Generated by Django 5.2.15 on 2026-09-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0008_alter_session_image_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="memeimage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booth_images",
                to="memz.session",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="booth_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("topics", "topics"),
                    ("same_meme", "same_meme"),
                    ("relaxed", "relaxed"),
                    ("photo_booth", "photo_booth"),
                ],
                default="normal",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("lobby", "lobby"),
                    ("booth", "booth"),
                    ("playing", "playing"),
                    ("finished", "finished"),
                    ("abandoned", "abandoned"),
                ],
                default="lobby",
                max_length=10,
            ),
        ),
    ]
