# Generated by Django 5.2.15 on 2026-09-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0009_memeimage_session_session_booth_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memeimage",
            name="booth_taken_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booth_photos",
                to="memz.player",
            ),
        ),
    ]
