# Generated by Django 5.2.15 on 2026-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memz", "0010_memeimage_booth_taken_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="booth_extensions",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
