services:
  - type: web
    name: mysite
    runtime: python
    plan: starter
    branch: main
    buildCommand: ./build.sh
    startCommand: python manage.py migrate && python manage.py createsuperuser --noinput || true && gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: PERSISTENT_ROOT
        value: /var/data
      - key: ALLOWED_HOSTS
        value: mysite-0tu0.onrender.com,babook.co.il,www.babook.co.il
      - key: CSRF_TRUSTED_ORIGINS
        value: https://mysite-0tu0.onrender.com,https://babook.co.il,https://www.babook.co.il
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
    disk:
      name: mysite-disk
      mountPath: /var/data
      sizeGB: 1
