# Generated by Django 5.2.15 on 2026-09-21 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import exo.models_reference


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExoAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=40, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MTP", "MTP"),
                            ("SCALE", "SCALE"),
                            ("IDEAS", "IDEAS"),
                            ("EXTRA", "Extra"),
                        ],
                        max_length=6,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name_he", models.CharField(blank=True, max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("short_def_he", models.TextField(blank=True)),
                ("short_def_en", models.TextField(blank=True)),
                ("prompt_hint_he", models.TextField(blank=True)),
                ("prompt_hint_en", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("category", "order", "key"),
            },
            bases=(exo.models_reference.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NewspaperStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=40, unique=True)),
                ("name_he", models.CharField(blank=True, max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("description_he", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("css_class", models.CharField(default="paper-classic", max_length=60)),
                ("supports_rtl", models.BooleanField(default=True)),
                ("supports_ltr", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "key"),
            },
            bases=(exo.models_reference.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("interview", "Interview"),
                            ("brainstorm", "Brainstorm"),
                            ("options", "Options"),
                            ("output", "Output"),
                        ],
                        default="interview",
                        max_length=12,
                    ),
                ),
                ("language", models.CharField(default="he", max_length=2)),
                ("mtp", models.TextField(blank=True)),
                ("special", models.TextField(blank=True)),
                ("unique", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("downstream_stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exo_concepts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("position", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="AiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task", models.CharField(max_length=40)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("ok", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exo_ai_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_calls",
                        to="exo.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BrainstormEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="exo.concept",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="exo.exoattribute",
                    ),
                ),
            ],
            options={
                "ordering": ("attribute__category", "attribute__order", "id"),
            },
        ),
        migrations.CreateModel(
            name="GeneratedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("research_note", models.TextField(blank=True)),
                ("is_selected", models.BooleanField(default=False)),
                ("is_user_authored", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exo.exoattribute",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exo.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("attribute__category", "attribute__order", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="exo.concept",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="LearnResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                ("title_he", models.CharField(blank=True, max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("body_he", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                ("youtube_url_he", models.URLField(blank=True)),
                ("youtube_url_en", models.URLField(blank=True)),
                ("book_reference_he", models.CharField(blank=True, max_length=200)),
                ("book_reference_en", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="exo.exoattribute",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "key"),
            },
            bases=(exo.models_reference.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="he", max_length=2)),
                (
                    "default_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exo_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exo_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField(blank=True)),
                ("document_body", models.TextField(blank=True)),
                ("language", models.CharField(default="he", max_length=2)),
                ("exponential_score", models.PositiveIntegerField(blank=True, null=True)),
                ("score_rationale", models.TextField(blank=True)),
                ("stress_test_feedback", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public forever"),
                            ("timed", "Public until a time"),
                            ("specific", "Specific people"),
                            ("private", "Only me"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("public_until", models.DateTimeField(blank=True, null=True)),
                ("hidden_by_admin", models.BooleanField(default=False)),
                ("edited_by_owner", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release",
                        to="exo.concept",
                    ),
                ),
                (
                    "newspaper_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releases",
                        to="exo.newspaperstyle",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True, related_name="exo_shared_releases", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PressReleaseLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_rows",
                        to="exo.pressrelease",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exo_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release", "user"), name="exo_one_like_per_person"
                    )
                ],
            },
        ),
    ]
