# Generated by Django 5.2.15 on 2026-09-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exo", "0002_exo_members_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicall",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_calls",
                to="exo.exoattribute",
            ),
        ),
    ]
