# Generated by Django 5.2.15 on 2026-09-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exo", "0003_aicall_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brainstormentry",
            options={"ordering": ("attribute__order", "id")},
        ),
        migrations.AlterModelOptions(
            name="exoattribute",
            options={"ordering": ("order", "key")},
        ),
        migrations.AlterModelOptions(
            name="generatedoption",
            options={"ordering": ("attribute__order", "order", "id")},
        ),
    ]
