# Generated by Django 5.2.15 on 2026-09-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exo", "0004_framework_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="mtp_note",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name="concept",
            name="mtp",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
