# Generated by Django 5.2.15 on 2026-09-30 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exo", "0006_mtp_guidance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="ai_needs_open_window",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("window_hours", models.PositiveIntegerField(default=24)),
                ("is_closed", models.BooleanField(default=False)),
                ("max_joins", models.PositiveIntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exo_cohorts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-starts_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="concept",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concepts",
                to="exo.cohort",
            ),
        ),
        migrations.CreateModel(
            name="CohortMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="exo.cohort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exo_cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-joined_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohort", "user"), name="exo_one_join_per_cohort"
                    )
                ],
            },
        ),
    ]
