# Generated by Django 5.2.15 on 2026-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exo", "0007_workshop_cohorts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressrelease",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public forever"),
                    ("timed", "Public until a time"),
                    ("cohort", "My workshop group"),
                    ("specific", "Specific people"),
                    ("private", "Only me"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
