# Generated by Django 5.2.15 on 2026-09-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=32)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_consents', to='sensorlab.sensorlabprofile')),
            ],
            options={
                'verbose_name': 'sensor consent',
                'verbose_name_plural': 'sensor consents',
                'unique_together': {('profile', 'sensor')},
            },
        ),
    ]
