# Generated by Django 5.2.15 on 2026-09-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0002_sensorconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title_en', models.CharField(max_length=120)),
                ('title_he', models.CharField(blank=True, max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_he', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('title_en', models.CharField(max_length=120)),
                ('title_he', models.CharField(blank=True, max_length=120)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_he', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('live_sensor', 'Live sensor'), ('video_tracking', 'Video tracking'), ('signal_generator', 'Signal generator')], default='live_sensor', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('prerequisite_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='sensorlab.lab')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='sensorlab.track')),
            ],
            options={
                'ordering': ('order', 'slug'),
                'unique_together': {('track', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_en', models.TextField(blank=True)),
                ('instructions_he', models.TextField(blank=True)),
                ('requested_hz', models.PositiveIntegerField(default=60)),
                ('max_duration_ms', models.PositiveIntegerField(default=10000)),
                ('trigger_kind', models.CharField(choices=[('manual', 'Manual'), ('threshold', 'Threshold')], default='manual', max_length=10)),
                ('trigger_threshold', models.FloatField(blank=True, null=True)),
                ('uses_signal_generator', models.BooleanField(default=False)),
                ('tone_frequency_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('strobe_rate_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='sensorlab.lab')),
            ],
            options={
                'verbose_name': 'experiment configuration',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('intro', 'Intro'), ('learn', 'Learn'), ('analysis', 'Analysis')], default='intro', max_length=10)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('formula', 'Formula'), ('callout', 'Callout')], default='text', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('body_en', models.TextField(blank=True)),
                ('body_he', models.TextField(blank=True)),
                ('media', models.ImageField(blank=True, upload_to='sensorlab/content/')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='sensorlab.lab')),
            ],
            options={
                'ordering': ('step', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnalysisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation', models.CharField(choices=[('peak', 'Peak'), ('mean', 'Mean'), ('slope', 'Slope'), ('period', 'Period'), ('fft_peak', 'FFT peak'), ('curve_fit', 'Curve fit'), ('area', 'Area')], max_length=12)),
                ('expected_source', models.CharField(choices=[('constant', 'A known constant'), ('formula', "Derived from the student's own inputs")], default='constant', max_length=10)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('expected_formula', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('pass_tolerance', models.FloatField(default=10.0, help_text='Percent error still counted a pass')),
                ('explanation_en', models.TextField(blank=True)),
                ('explanation_he', models.TextField(blank=True)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='sensorlab.lab')),
            ],
            options={
                'verbose_name': 'analysis configuration',
            },
        ),
        migrations.CreateModel(
            name='PredictionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('numeric', 'Numeric'), ('free_text', 'Free text'), ('graph_sketch', 'Graph sketch')], default='multiple_choice', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prompt_en', models.TextField()),
                ('prompt_he', models.TextField(blank=True)),
                ('correct_value', models.FloatField(blank=True, null=True)),
                ('tolerance', models.FloatField(default=10.0, help_text='Percent')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_questions', to='sensorlab.lab')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PredictionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=200)),
                ('text_he', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sensorlab.predictionquestion')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SensorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('accelerometer', 'Accelerometer'), ('linear-accelerometer', 'Linear Accelerometer'), ('gyroscope', 'Gyroscope'), ('magnetometer', 'Magnetometer'), ('barometer', 'Barometer'), ('light', 'Light'), ('proximity', 'Proximity'), ('microphone', 'Microphone'), ('camera', 'Camera'), ('gps', 'Gps')], max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('axis_filter', models.CharField(blank=True, help_text="e.g. 'z' when only one axis matters", max_length=8)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_requirements', to='sensorlab.experimentconfig')),
            ],
            options={
                'unique_together': {('config', 'sensor')},
            },
        ),
    ]
