# Generated by Django 5.2.15 on 2026-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0003_track_lab_experimentconfig_contentblock_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
