# Generated by Django 5.2.15 on 2026-09-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0004_alter_lab_unique_together_alter_lab_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisconfig',
            options={'ordering': ('lab_id',), 'verbose_name': 'analysis configuration'},
        ),
        migrations.AlterModelOptions(
            name='experimentconfig',
            options={'ordering': ('lab_id',), 'verbose_name': 'experiment configuration'},
        ),
        migrations.AlterModelOptions(
            name='sensorrequirement',
            options={'ordering': ('config_id', 'sensor')},
        ),
    ]
