# Generated by Django 5.2.15 on 2026-09-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0007_repair_free_fall_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('curve_points', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_answers', to='sensorlab.labattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sensorlab.predictionquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sensorlab.predictionchoice')),
            ],
            options={
                'ordering': ('question__order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='one_prediction_per_question')],
            },
        ),
    ]
