# Generated by Django 5.2.15 on 2026-09-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0008_predictionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('accelerometer', 'Accelerometer'), ('linear-accelerometer', 'Linear Accelerometer'), ('gyroscope', 'Gyroscope'), ('magnetometer', 'Magnetometer'), ('barometer', 'Barometer'), ('light', 'Light'), ('proximity', 'Proximity'), ('microphone', 'Microphone'), ('camera', 'Camera'), ('gps', 'Gps')], max_length=32)),
                ('requested_hz', models.PositiveIntegerField()),
                ('achieved_hz', models.FloatField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('samples', models.JSONField(default=list)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='sensorlab.labattempt')),
            ],
            options={
                'ordering': ('-recorded_at', '-id'),
                'indexes': [models.Index(fields=['attempt', 'sensor'], name='sensorlab_s_attempt_04ce80_idx')],
            },
        ),
    ]
