# Generated by Django 5.2.15 on 2026-09-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorlab', '0009_sensorrecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation', models.CharField(max_length=12)),
                ('measured_value', models.FloatField()),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('error_percent', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('prediction_was_correct', models.BooleanField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='sensorlab.labattempt')),
            ],
            options={
                'ordering': ('-computed_at',),
            },
        ),
    ]
