"""Seed the public bank, decks and topics, once (spec §6.1, §12.7, §14.3;
building_an_app.md "Data").

Public packs and their images come from `memz/seed_assets/<pack-slug>/`,
keyed by `MemeImage.seed_key` (the file's relative path). The rule is
check-before-create: a key that already has a row is left alone, whatever
an admin did to that row since (title edited, image retired to `rejected`),
and nothing is ever deleted. Deleting a row makes the next run recreate it;
to take an image out of the public bank, retire it in the admin instead.

Caption decks and topics (SPR-Z.4) don't have a per-row key the way images
do, so the rule is coarser but the same in spirit: a deck or the topic pool
is seeded **only while it's empty**. The moment an admin has added, edited,
or removed a single card, this command leaves that deck alone forever —
never re-adds a removed card, never reintroduces one under a new id.

Runs on every deploy from render.yaml (from SPR-Z.7), like every `seed_*`
command in this repo, and is safe to run any number of times.

The images shipped in SPR-Z.1 were generated placeholders (flat shapes,
`memz/seed_assets/make_assets.py`); SPR-Z.7 (ACT-Z.1) replaces them with
our own AI-illustrated art across 8 packs (`generate_bank_images.py`),
under Rule 6.1.1 (licensed or our own, never a copyrighted meme
template, never a real person's photo). The old placeholder rows are
retired — not deleted — by `retire_placeholder_images`, a one-time,
re-runnable command, not by this seed (which never removes a row).

The Hebrew caption deck and topics below went through their tone review
in SPR-Z.7 (ACT-Z.4): the original 40/15 held up against Rule 9.1
(playful, never mean) with nothing needing a rewrite, so the review's
actual output was the expansion beneath them, in the same voice.
"""

from pathlib import Path

from django.core.files import File
from django.core.management.base import BaseCommand

from memz.models import CaptionCard, CaptionDeck, MemeImage, Pack, PackImage, Topic

HEBREW = CaptionDeck.HEBREW

ASSETS = Path(__file__).resolve().parents[2] / "seed_assets"

# (slug, name, description, order). A public pack is a category (data_model.md).
# SPR-Z.7 (ACT-Z.1): four new packs alongside the original four, matched to
# the illustration batch generated by generate_bank_images.py.
PACKS = [
    ("family", "משפחה", "רגעים מהבית: ארוחות, טיולים, ימי ראשון.", 0),
    ("animals", "חיות", "חתולים, כלבים ושאר חברים עם פרצוף.", 1),
    ("work", "עבודה", "פגישות, מיילים, וכל מה שביניהם.", 2),
    ("school", "בית ספר", "שיעורים, מבחנים והפסקות.", 3),
    ("friends", "חברים", "מפגשים, בדיחות פנימיות ותמונות קבוצתיות.", 4),
    ("food", "אוכל", "ארוחות, חטיפים וקינוחים שאי אפשר לעמוד בפניהם.", 5),
    ("holidays", "חגים", "נרות, מתנות וערבי חג משפחתיים.", 6),
    ("sports", "ספורט", "אימונים, משחקים ורגעי ניצחון.", 7),
    # Post-epic content activity (ACT-Z.5): stock reaction photos -- shocked,
    # annoyed, facepalm, laughing, confused, disappointed -- standing in for
    # the copyrighted meme templates and celebrity photos that were asked for
    # and declined (spec Rule 6.1.1).
    ("reactions", "תגובות", "פרצופים לכל מצב: מופתעים, מתוסכלים, צוחקים.", 8),
]

IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp"}

# ACT-Z.4: a first, family-safe Hebrew caption deck (spec §5.2, Cards mode).
CAPTION_CARDS_HE = [
    "כשאמא מתקשרת בדיוק כשמדברים עליה",
    "כשמישהו אומר \"בוא נדבר רגע\"",
    "אני אחרי קפה ראשון של הבוקר",
    "כשהוואטסאפ הקבוצתי מתחיל לרעוד ב-2 בלילה",
    "כשמישהו שואל \"מה שלומך\" ומתכוון לזה",
    "הפרצוף שלי כשהאינטרנט נופל באמצע פגישה",
    "כשמוצאים חמישים שקל בכיס של מכנס ישן",
    "כשאומרים \"רק עוד חמש דקות\" בבוקר",
    "כשמישהו לוקח את החטיף האחרון בלי לשאול",
    "אני מנסה להיראות עסוק כשהבוס עובר ליד",
    "כשהילד שואל \"עוד כמה זמן\" בדקה השנייה של הנסיעה",
    "כשסוף סוף מוצאים חניה קרוב",
    "כשמישהו שר לא במקום בשיר יום הולדת",
    "הפרצוף כשמבינים שזו יום שני, לא שלישי",
    "כשמישהו אומר \"אני לא כועס\" בטון שאומר בדיוק ההפך",
    "כשהמקרר ריק אבל בודקים אותו בכל זאת",
    "כשמישהו שואל אם אפשר לוותר על הישיבה",
    "אני שומע את המילה \"בקיצור\" ויודע שזה לא יהיה בקיצור",
    "כשהתראה על הטלפון מפריעה בדיוק בזמן הכי לא נוח",
    "כשמנסים להירדם ופתאום נזכרים בכל מה שצריך לעשות מחר",
    "כשמישהו מבקש \"רק שאלה קטנה\" לפני שדוחפים שאלה ענקית",
    "כשהמורה אומרת \"בחינת פתע\"",
    "אני מנסה לזכור איפה חניתי",
    "כשמישהו אומר \"זה ממש לא קשה\" ומתחיל להסביר משהו מסובך",
    "כשמישהו פותח פה עם אוכל ומדבר בכל זאת",
    "כשמגלים שהיום שכולם ציפו לו סוף סוף הגיע",
    "כשמישהו שואל \"אתה בטוח?\" בפעם השלישית",
    "הפרצוף כשמבינים שהשכחתי את הטלפון בבית",
    "כשמישהו מבטיח \"עוד חמש דקות ואני שם\"",
    "כשהגשם מתחיל בדיוק כשיוצאים בלי מטרייה",
    "כשמישהו אומר \"בואו נעשה את זה מהר\" ולוקח שעתיים",
    "כשמישהו שם לי משימה חדשה חמש דקות לפני שיוצאים",
    "אני שומע מישהו לועס צ'יפס לידי בשקט מוחלט",
    "כשמישהו שואל למה לא עניתי, ואני הייתי ממש שם",
    "כשגומרים סדרה שלמה בלילה אחד ומתחרטים בבוקר",
    "כשמישהו אומר \"תזכיר לי\" ואני יודע שגם אני אשכח",
    "הפרצוף שלי כשמנצחים במשחק בגלל מזל בלבד",
    "כשמישהו מקליד \"תתקשר כשתתפנה\" ומתכוון עכשיו",
    "כשהילד נרדם בדיוק כשמגיעים הביתה",
    "כשמישהו אומר \"קצת פרגון לא יזיק\" באמצע ריב",
    # SPR-Z.7 / ACT-Z.4: expansion after the tone review. The first 40 above
    # were read again against Rule 9.1 (playful, never mean) and left as-is —
    # nothing there needed rewriting, so the review's real output is this
    # second batch, in the same voice: everyday, self-deprecating, nobody
    # the butt of the joke but the reader.
    "כשמישהו שואל \"עוד לא ענית?\" בדיוק כשהתחלתי לענות",
    "הפרצוף שלי כשמישהו לוקח את המקום שלי בחנייה",
    "כשהילד שואל \"למה\" בפעם העשירית ברצף",
    "כשמישהו אומר \"בואי נדבר בעוד חמש דקות\" ועוברות שעתיים",
    "כשמגלים שהפגישה הייתה יכולה להיות מייל",
    "כשמישהו שם לב שאני עונה \"בסדר\" אבל לא בסדר",
    "כשמישהו מציע לעזור בדיוק כשכבר סיימתי לבד",
    "אני שומע את עצמי אומר \"עוד חמש דקות ואני ישן\" בשעה 2 בלילה",
    "כשמישהו מבטל תוכנית ואני שמח בסתר",
    "כשמנסים להסביר חלום ונשמע הזוי לגמרי",
    "כשהמלצר שואל \"עוד משהו?\" וכבר הזמנתי יותר מדי",
    "כשמישהו קורא לי בשם הלא נכון בפעם השלישית",
    "הפרצוף כשקוראים לי בדיוק כשנרדמתי",
    "כשמישהו אומר \"זה לא באמת יקר\" על משהו יקר מאוד",
    "כשמנסים לזכור אם נעלתי את הדלת",
    "כשמישהו שואל \"מתי מתחתנים\" בארוחת המשפחה",
    "כשמישהו מציק לי שאני תמיד מאחר, ואני מגיע בזמן דווקא היום",
    "הפרצוף שלי כשמישהו אוכל את מה שסימנתי \"שלי\" במקרר",
    "כשמישהו שואל \"ראית את ההודעה שלי\" ולא ראיתי",
    "כשמנסים להיזכר בשם של מישהו שפוגשים בפעם השלישית",
    "כשמישהו מבטיח \"פעם אחרונה שאני עושה את זה\" בפעם העשירית",
    "כשמגלים שהמופע שרצית לראות כבר עבר",
    "כשמישהו שואל \"את בטח לחוצה?\" ואני בכלל לא הייתי",
    "כשהגיע הזמן לקום אבל השמיכה חמה מדי",
    "כשמישהו שואל \"מה אתה עושה הערב\" ואין לי שום תוכנית",
    "כשהילד מתעורר בדיוק כשגמרתי להרדים אותו",
    "כשמישהו שואל \"מה קרה\" ואני לא יודע איך להתחיל להסביר",
    "כשמישהו מגיע בלי להודיע בדיוק כשהבית בבלגן",
    "כשמישהו אומר \"סמוך עליי\" ואני כבר לא כל כך בטוח",
    "כשמישהו לוחץ על הכפתור לפני שהמעלית בכלל הגיעה",
    "כשמישהו שואל \"את/ה בטוח/ה שזה נכון?\" ואני פתאום לא בטוח",
    "כשמישהו מספר בדיחה ואני לא מבין את הפאנץ' עד עשר שניות אחרי",
    "הפרצוף כשמישהו נכנס בלי לדפוק",
    "כשמישהו שואל \"למה את/ה כל כך שקט/ה\" ואין תשובה טובה",
    "כשמישהו שם לי מטלה ברגע האחרון ומצפה שאשמח",
    "כשמישהו מבטיח להחזיר כסף ולא מזכיר את זה שוב",
    "כשמישהו אומר \"תירגע\" ואני נהיה עצבני יותר",
    "כשמישהו שואל \"את/ה בא/ה?\" ואני עדיין בפיג'מה",
    "כשמישהו מדליק אור בזמן שאני מנסה להירדם",
    "כשמישהו אומר \"רק עוד פרק אחד\" ואז עוד חמישה",
    "כשמישהו שואל \"מה שלום העבודה\" בפגישה משפחתית",
    "כשמישהו שם עוגה בעבודה ואומר \"רק פרוסה קטנה\"",
    "כשמישהו שואל \"מתי בדיוק\" ואני עדיין לא מוכן/ה להגיד",
    "כשגומרים לנקות ומישהו נכנס עם נעליים בוציות",
    "כשמישהו שואל \"זה הכל?\" על משהו שלקח שעות להכין",
    "כשמישהו מזכיר משהו מביך משנים",
    "כשמישהו שואל \"מה חדש\" ואין באמת מה לענות",
    "כשמישהו שם לי לייק אבל לא עונה בהודעה",
    "כשמישהו שואל \"בא לך לצאת?\" בדיוק כשהתכוונתי להישאר בבית",
    "כשמישהו שם את זה עלי בקבוצה ומצפה לתגובה מיידית",
    "כשמישהו שואל \"מה אתה חושב שקורה פה\" ואין לי מושג",
    "כשמישהו שואל \"למה את/ה מתחיל/ה עכשיו\" בשעה מאוחרת מדי",
    "כשמישהו מבטיח \"אני כבר בדרך\" ועדיין לא יצא מהבית",
    "כשמישהו שם לב שהשתנה משהו ואני לא רוצה לספר",
    "כשמישהו שואל \"מה זה הריח הזה\" ואני יודע בדיוק ולא רוצה לענות",
    "כשמישהו שואל \"מוכנים?\" ואני עדיין מחפש נעליים",
    "כשמישהו שואל \"מה השעה\" בדיוק כשלא רוצים לדעת",
]

TOPICS_HE = [
    "יום שני בבוקר",
    "פקקים",
    "חופש גדול",
    "ערב שישי",
    "הפסקת קפה",
    "ראש השנה",
    "יום ראשון בעבודה",
    "שיעורי בית",
    "טיול משפחתי",
    "ליל הסדר",
    "יום גשום",
    "מבחנים",
    "חתונה",
    "יום הולדת",
    "חופשה בים",
    # SPR-Z.7 expansion, same voice: a scene, a moment, an occasion — never
    # a punchline on its own, always something to caption.
    "יום שישי בבוקר בשוק",
    "ערב לפני מבחן",
    "הגעה לחתונה של קרוב רחוק",
    "פגישת עבודה שיכלה להיות מייל",
    "ילד שמסרב לישון",
    "יום גיבוש",
    "מסיבת הפתעה",
    "רגע לפני הגשת עבודה",
    "יום ראשון בבוקר אחרי חג",
    "אירוח לא מתוכנן",
    "יום הולדת עגול",
    "טיסה עם ילדים קטנים",
    "בוקר שבת",
    "ערב בחירות",
    "יום ראשון של שנת לימודים",
    "פיקניק בפארק",
    "יום גשום בלי סוכריות",
    "ליל שבת אצל הסבתא",
    "מסיבת יום הולדת לילד",
    "יום המכביר של אימונים",
]


class Command(BaseCommand):
    help = "Seed memz's public packs, bank, caption deck and topics, one time only."

    def handle(self, *args, **options):
        verbosity = int(options.get("verbosity", 1))
        created_packs = created_images = linked = skipped = 0

        for slug, name, description, order in PACKS:
            pack, made = Pack.objects.get_or_create(
                owner=None, slug=slug,
                defaults={"name": name, "description": description, "is_public": True, "order": order},
            )
            created_packs += int(made)

            folder = ASSETS / slug
            files = sorted(p for p in folder.iterdir() if p.suffix.lower() in IMAGE_SUFFIXES) if folder.is_dir() else []
            for position, path in enumerate(files):
                key = f"{slug}/{path.name}"
                image = MemeImage.objects.filter(seed_key=key).first()
                if image is None:
                    is_placeholder = path.stem.startswith("placeholder-")
                    is_stock = "-stock-" in path.stem
                    if is_placeholder:
                        note = "seeded placeholder (SPR-Z.1); replaced by real content in SPR-Z.7"
                    elif is_stock:
                        note = (
                            "stock photo (spec Rule 6.1.1): Pexels, licensed free for commercial "
                            "use with no attribution required, an ordinary model, never a public "
                            "figure -- source URL recorded in seed_assets/stock_manifest.json"
                        )
                    else:
                        note = (
                            "AI-illustrated (SPR-Z.7, spec Rule 6.1.1): our own generated art, "
                            "not a photo of a real person and not a copyrighted meme template"
                        )
                    image = MemeImage(
                        owner=None, visibility=MemeImage.PUBLIC, moderation_status=MemeImage.APPROVED,
                        moderation_note=note,
                        seed_key=key, title=path.stem.replace("-", " ").replace("_", " "),
                    )
                    with path.open("rb") as fh:
                        image.file.save(path.name, File(fh), save=True)
                    created_images += 1
                else:
                    skipped += 1
                _link, made = PackImage.objects.get_or_create(pack=pack, image=image, defaults={"order": position})
                linked += int(made)

        deck, deck_made = CaptionDeck.objects.get_or_create(
            owner=None, name="חפיסה ראשונה", defaults={"is_public": True, "language": HEBREW},
        )
        cards_created = 0
        if not deck.cards.exists():   # coarse one-time rule: seed only an empty deck
            CaptionCard.objects.bulk_create([
                CaptionCard(deck=deck, text=text, order=i) for i, text in enumerate(CAPTION_CARDS_HE)
            ])
            cards_created = len(CAPTION_CARDS_HE)

        topics_created = 0
        if not Topic.objects.filter(owner=None, is_public=True).exists():
            Topic.objects.bulk_create([
                Topic(text=text, owner=None, is_public=True, language=HEBREW) for text in TOPICS_HE
            ])
            topics_created = len(TOPICS_HE)

        if verbosity:
            self.stdout.write(
                f"seed_memz: packs +{created_packs}, images +{created_images} "
                f"(left alone {skipped}), links +{linked}, "
                f"caption cards +{cards_created}, topics +{topics_created}"
            )
