# Generated by Django 5.2.15 on 2026-10-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("improv", "0001_gate_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChordQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="m7, maj7, 7, m7b5, 7alt ...", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "intervals",
                    models.JSONField(
                        help_text="Semitones above the root, sorted, from 0: [0,3,7,10]."
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        help_text='Semitone to role: {"0": "root", "3": "third", "10": "seventh"}.'
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Other spellings the chart parser accepts.",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("major", "major"),
                            ("minor", "minor"),
                            ("dominant", "dominant"),
                            ("diminished", "diminished"),
                            ("half_diminished", "half-diminished"),
                            ("suspended", "suspended"),
                            ("augmented", "augmented"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "chord qualities",
                "ordering": ["sort_order", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(unique=True)),
                (
                    "intervals",
                    models.JSONField(help_text="Semitones above the root, sorted, from 0."),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("major_modes", "major modes"),
                            ("melodic_minor_modes", "melodic minor modes"),
                            ("harmonic_minor_modes", "harmonic minor modes"),
                            ("pentatonic", "pentatonic"),
                            ("blues", "blues"),
                            ("symmetric", "symmetric"),
                        ],
                        max_length=24,
                    ),
                ),
                ("mode_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "parent_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modes",
                        to="improv.scale",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChordScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "preference",
                    models.PositiveSmallIntegerField(help_text="1 is the first choice."),
                ),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "chord_quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chord_scales",
                        to="improv.chordquality",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chord_scales",
                        to="improv.scale",
                    ),
                ),
            ],
            options={
                "ordering": ["chord_quality", "preference"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chord_quality", "scale"), name="improv_chordscale_unique"
                    )
                ],
            },
        ),
    ]
