# Generated by Django 5.2.15 on 2026-10-04 18:00

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import improv.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0002_theory_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("slug", models.SlugField(max_length=60, unique=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("jazz", "jazz"),
                            ("blues", "blues"),
                            ("pop", "pop"),
                            ("rock", "rock"),
                            ("gospel", "gospel"),
                            ("latin", "latin"),
                            ("funk", "funk"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "feel",
                    models.CharField(
                        choices=[
                            ("swing", "swing"),
                            ("straight", "straight"),
                            ("shuffle", "shuffle"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "swing_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="0.50 is straight, about 0.67 is a hard swing.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.50")),
                            django.core.validators.MaxValueValidator(Decimal("0.75")),
                        ],
                    ),
                ),
                (
                    "time_signature",
                    models.CharField(
                        default="4/4",
                        max_length=5,
                        validators=[improv.models._signature_is_playable],
                    ),
                ),
                (
                    "default_tempo",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "min_tempo",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "max_tempo",
                    models.PositiveSmallIntegerField(
                        default=200,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "drums",
                    models.JSONField(
                        help_text="{instrument: [16 strengths 0..1]} for a 4/4 bar. See improv/grooves.py."
                    ),
                ),
                ("bass", models.JSONField(help_text='{"rule": "walking", "range": [33, 55]}')),
                (
                    "comp",
                    models.JSONField(
                        help_text='{"rhythm": [[0, 6], [6, 4]], "voicing": "shell", "register": [52, 76]}'
                    ),
                ),
                ("is_preset", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improv_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="Progression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("jazz", "jazz"),
                            ("blues", "blues"),
                            ("pop", "pop"),
                            ("rock", "rock"),
                            ("gospel", "gospel"),
                            ("latin", "latin"),
                            ("funk", "funk"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "chart",
                    models.TextField(
                        help_text="The only copy of the harmony. | Dm7 | G7 | Cmaj7 | % | See docs/improv/api.md, Chart grammar.",
                        validators=[
                            improv.models._not_blank,
                            django.core.validators.MaxLengthValidator(20000),
                        ],
                    ),
                ),
                (
                    "home_key",
                    models.CharField(
                        help_text="The key the chart is written in.",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                (
                    "time_signature",
                    models.CharField(
                        default="4/4",
                        max_length=5,
                        validators=[improv.models._signature_is_playable],
                    ),
                ),
                (
                    "default_tempo",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_preset", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improv_progressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progressions",
                        to="improv.style",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="progressions", to="improv.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty", django.db.models.functions.text.Lower("title")],
            },
        ),
    ]
