# Generated by Django 5.2.15 on 2026-10-05 12:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0003_band_and_charts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "daily_goal_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                (
                    "latency_offset_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Measured by calibration (SPR-I.3.4). Judging subtracts it from every note time.",
                        validators=[
                            django.core.validators.MinValueValidator(-500),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "midi_input_name",
                    models.CharField(
                        blank=True,
                        help_text="The keyboard last used, by name: a port's id is not promised to stay the same.",
                        max_length=120,
                    ),
                ),
                (
                    "note_names",
                    models.CharField(
                        choices=[("sharps", "sharps (C#)"), ("flats", "flats (Db)")],
                        default="sharps",
                        max_length=6,
                    ),
                ),
                (
                    "demo_output",
                    models.CharField(
                        choices=[
                            ("piano", "the piano, over MIDI"),
                            ("laptop", "the laptop, as a plain tone"),
                        ],
                        default="piano",
                        max_length=6,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Jerusalem",
                        help_text="IANA name. The site runs on UTC and a streak is made of the player's own days.",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improv_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
