# Generated by Django 5.2.15 on 2026-10-05 16:45

import django.core.validators
import django.db.models.deletion
import improv.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0004_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "active_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Time the band was running or a note was played, not time the tab was open.",
                        validators=[django.core.validators.MaxValueValidator(86400)],
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="improv.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Take",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chart",
                    models.TextField(
                        help_text="Snapshot of the chart as played.",
                        validators=[
                            improv.models._not_blank,
                            django.core.validators.MaxLengthValidator(20000),
                        ],
                    ),
                ),
                (
                    "home_key",
                    models.CharField(
                        help_text="The key the chart text is written in.",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key it was played in.",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                (
                    "time_signature",
                    models.CharField(
                        default="4/4",
                        max_length=5,
                        validators=[improv.models._signature_is_playable],
                    ),
                ),
                (
                    "tempo",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ]
                    ),
                ),
                (
                    "swing_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.50")),
                            django.core.validators.MaxValueValidator(Decimal("0.75")),
                        ],
                    ),
                ),
                (
                    "loop_from",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="First bar played, 0-based."
                    ),
                ),
                (
                    "loop_to",
                    models.PositiveSmallIntegerField(help_text="One past the last bar played."),
                ),
                ("started_at", models.DateTimeField()),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(21600000)]
                    ),
                ),
                (
                    "bars",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="{t_ms, type: on/off, note, velocity} as the MIDI arrived.",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
                (
                    "judge_version",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_kept", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takes",
                        to="improv.player",
                    ),
                ),
                (
                    "progression",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="takes",
                        to="improv.progression",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takes",
                        to="improv.practicesession",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="takes",
                        to="improv.style",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
