# Generated by Django 5.2.15 on 2026-10-05 17:50

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import improv.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0005_practicesession_take"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, help_text="Within the lesson."),
                ),
                ("title", models.CharField(max_length=100, validators=[improv.models._not_blank])),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "instructions",
                    models.TextField(
                        validators=[
                            improv.models._not_blank,
                            django.core.validators.MaxLengthValidator(4000),
                        ]
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                (
                    "tempo",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ]
                    ),
                ),
                (
                    "bars",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="How much to play.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(64),
                        ],
                    ),
                ),
                (
                    "scoring_kind",
                    models.CharField(
                        choices=[
                            ("chord_tones_on_beats", "chord tones on beats"),
                            ("guide_tones", "guide tones"),
                            ("scale_only", "scale only"),
                            ("approach_notes", "approach notes"),
                            ("rhythm_motif", "rhythm motif"),
                            ("call_and_response", "call and response"),
                            ("comping_voicings", "comping voicings (a later version)"),
                            ("free_play", "free play"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "scoring_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='The judge reads these by kind, e.g. {"beats": [1, 3]}. See improv/teaching.py.',
                    ),
                ),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=70, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "xp",
                    models.PositiveSmallIntegerField(
                        default=10, validators=[django.core.validators.MaxValueValidator(1000)]
                    ),
                ),
                (
                    "daily_eligible",
                    models.BooleanField(default=False, help_text="May the daily workout pick it."),
                ),
                (
                    "progression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises",
                        to="improv.progression",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="improv.style",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson__track", "lesson__order", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="take",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="takes",
                to="improv.exercise",
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("chord_tones", "chord tones"),
                            ("guide_tones", "guide tones"),
                            ("scales_modes", "scales and modes"),
                            ("approach_notes", "approach notes"),
                            ("rhythm_motifs", "rhythm motifs"),
                            ("call_and_response", "call and response"),
                            ("voicings_comping", "voicings and comping"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(help_text="Position within the track.")),
                ("title", models.CharField(max_length=100, validators=[improv.models._not_blank])),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One line for the card.",
                        max_length=200,
                        validators=[improv.models._not_blank],
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="The short teaching text, in markdown.",
                        validators=[
                            improv.models._not_blank,
                            django.core.validators.MaxLengthValidator(20000),
                        ],
                    ),
                ),
                (
                    "authorship",
                    models.CharField(
                        choices=[
                            ("ai_drafted", "drafted by AI, not yet read"),
                            ("reviewed", "drafted by AI, read and corrected"),
                            ("avi_written", "written by Avi"),
                        ],
                        default="ai_drafted",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocks",
                        to="improv.lesson",
                    ),
                ),
                (
                    "progression",
                    models.ForeignKey(
                        blank=True,
                        help_text="The changes the lesson is taught over.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="improv.progression",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="improv.style",
                    ),
                ),
            ],
            options={
                "ordering": ["track", "order"],
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty means a standalone challenge or a daily-workout candidate.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="improv.lesson",
            ),
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, validators=[improv.models._not_blank])),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("demo", "demo"),
                            ("call", "call"),
                            ("answer", "answer"),
                            ("lick", "lick"),
                        ],
                        default="lick",
                        max_length=8,
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        help_text="[{midi, beat, length, velocity}]: beats counted from 0 at the start of the phrase."
                    ),
                ),
                (
                    "length_beats",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.25")),
                            django.core.validators.MaxValueValidator(Decimal("64")),
                        ],
                    ),
                ),
                (
                    "chart_context",
                    models.TextField(
                        blank=True,
                        help_text="The chords underneath, if it only makes sense over them.",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                (
                    "written_in_key",
                    models.CharField(
                        default="C",
                        help_text="So it can be transposed with the chart.",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                ("is_preset", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improv_phrases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="demo_phrase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="improv.phrase",
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("lesson", "order"), name="improv_exercise_lesson_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("track", "order"), name="improv_lesson_track_order_unique"
            ),
        ),
    ]
