# Generated by Django 5.2.15 on 2026-10-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0006_teaching"),
    ]

    operations = [
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("xp_awarded", models.PositiveSmallIntegerField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="improv.exercise",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="improv.player",
                    ),
                ),
                (
                    "take",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completion",
                        to="improv.take",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "exercise"),
                        name="improv_completion_player_exercise_unique",
                    )
                ],
            },
        ),
    ]
