# Generated by Django 5.2.15 on 2026-10-07 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0007_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="trainer_tempo",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="The scale trainer's tempo in bpm. Changing it on the screen saves it here.",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(160),
                ],
            ),
        ),
        migrations.CreateModel(
            name="ScaleFingering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "root_pc",
                    models.PositiveSmallIntegerField(
                        help_text="The tonic as a pitch class, C is 0.",
                        validators=[django.core.validators.MaxValueValidator(11)],
                    ),
                ),
                (
                    "hand",
                    models.CharField(
                        choices=[("L", "left hand"), ("R", "right hand")], max_length=1
                    ),
                ),
                (
                    "first_octave",
                    models.JSONField(
                        help_text="Seven fingers, one per scale degree, for the first octave. 1 is the thumb."
                    ),
                ),
                (
                    "next_octaves",
                    models.JSONField(help_text="Seven fingers for every later octave."),
                ),
                (
                    "last_note",
                    models.PositiveSmallIntegerField(
                        help_text="The finger on the top note.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "authorship",
                    models.CharField(
                        choices=[
                            (
                                "ai_drafted",
                                "taken from a published chart, not yet read at the piano",
                            ),
                            ("reviewed", "read and checked by Avi"),
                        ],
                        default="ai_drafted",
                        max_length=12,
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerings",
                        to="improv.scale",
                    ),
                ),
            ],
            options={
                "ordering": ["scale_id", "root_pc", "hand"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scale", "root_pc", "hand"),
                        name="improv_scalefingering_scale_key_hand_unique",
                    )
                ],
            },
        ),
    ]
