# Generated by Django 5.2.15 on 2026-10-07 14:04

import django.core.validators
import django.db.models.deletion
import improv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0008_scale_fingering_trainer_tempo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "root_pc",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(11)]
                    ),
                ),
                (
                    "octaves",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "notes_per_beat",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "tempo_bpm",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(160),
                        ]
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "pitch_accuracy",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "timing_accuracy",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "mean_offset_ms",
                    models.IntegerField(
                        help_text="Negative is early.",
                        validators=[
                            django.core.validators.MinValueValidator(-5000),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                ("passed", models.BooleanField(default=False, editable=False)),
                (
                    "missed_steps",
                    models.JSONField(
                        default=list,
                        help_text="0-based step numbers where a note was missed.",
                        validators=[improv.models._check_missed_steps],
                    ),
                ),
                (
                    "judge_version",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale_runs",
                        to="improv.player",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="improv.scale",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
