# Generated by Django 5.2.15 on 2026-10-07 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0009_scale_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("chord_position", "A chord in a position")],
                        default="chord_position",
                        max_length=24,
                    ),
                ),
                (
                    "key_pc",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(11)]
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                ("prompt", models.JSONField(default=dict)),
                ("answer", models.JSONField(blank=True, default=dict)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "wrong_tries",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(200)]
                    ),
                ),
                ("hint_used", models.BooleanField(default=False)),
                ("skipped", models.BooleanField(default=False)),
                (
                    "response_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(3600000)],
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_attempts",
                        to="improv.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-answered_at", "-id"],
            },
        ),
    ]
