# Generated by Django 5.2.15 on 2026-10-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0010_drill_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("idea", "an idea"),
                            ("problem", "something is wrong"),
                            ("praise", "something I liked"),
                            ("other", "something else"),
                        ],
                        default="idea",
                        max_length=7,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        help_text="The improv screen they were on, e.g. /improv/play/.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="improv.player",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "feedback",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
