# Generated by Django 5.2.15 on 2026-10-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0011_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="path_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Position in the whole path, across tracks. Empty sorts after every numbered lesson, by level, track and order.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="current_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the player chose to be in the path: Today and Continue follow from here. Moves when they press Start here or play an exercise of another lesson.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players_here",
                to="improv.lesson",
            ),
        ),
    ]
