# Generated by Django 5.2.15 on 2026-10-10 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0013_lesson_level_four"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="reading_tempo",
            field=models.PositiveSmallIntegerField(
                default=72,
                help_text="The reading trainer's tempo in bpm. Changing it on the screen saves it here.",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(160),
                ],
            ),
        ),
        migrations.CreateModel(
            name="ReadingTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The major key, as written: C, F#, Bb.",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                (
                    "hands",
                    models.CharField(
                        choices=[("R", "right hand"), ("L", "left hand"), ("B", "both hands")],
                        max_length=1,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                (
                    "tempo_bpm",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(160),
                        ]
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("flow", "flow: the pulse never waits"),
                            ("step", "step: it waits for the right note"),
                        ],
                        default="flow",
                        max_length=4,
                    ),
                ),
                (
                    "curtain",
                    models.BooleanField(
                        default=False, help_text="Whether the notes behind the cursor were hidden."
                    ),
                ),
                (
                    "seed",
                    models.PositiveIntegerField(
                        help_text="The generator's seed: the same stage and seed give the same exercise."
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        default=list,
                        help_text="The exercise as written: {hand, step, acc, midi, beat, dur} per note.",
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="{t_ms, type: on/off, note, velocity} as the MIDI arrived.",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        default=list,
                        help_text="The judge's word on each written note: {state, timing, offset_ms, played}.",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "pitch_accuracy",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "timing_accuracy",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("passed", models.BooleanField(default=False, editable=False)),
                (
                    "judge_version",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_takes",
                        to="improv.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
