# Generated by Django 5.2.15 on 2026-10-10 14:36

import django.core.validators
import django.db.models.deletion
import improv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improv", "0014_reading_take"),
    ]

    operations = [
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("title", models.CharField(max_length=100, validators=[improv.models._not_blank])),
                (
                    "composer",
                    models.CharField(max_length=100, validators=[improv.models._not_blank]),
                ),
                (
                    "catalog",
                    models.CharField(blank=True, help_text="BWV 846, Anh. 114.", max_length=60),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 beginner to 5 advanced.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(help_text="Position within its level.")),
                (
                    "key",
                    models.CharField(
                        default="C",
                        help_text="The major key signature, as written.",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-G][#b]?m?$",
                                "A key is a note name with an optional # or b and an m for minor: C, Eb, F#m.",
                            )
                        ],
                    ),
                ),
                (
                    "beats_per_bar",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "bars",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                (
                    "tempo_bpm",
                    models.PositiveSmallIntegerField(
                        help_text="The tempo it is meant to be played at.",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "slow_bpm",
                    models.PositiveSmallIntegerField(
                        help_text="The slow practice tempo.",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        help_text="[{hand, step, acc, midi, beat, dur, bar, shown, voice, ties?, hold?}]: beats are absolute quarter notes from 0."
                    ),
                ),
                (
                    "blurb",
                    models.CharField(
                        blank=True,
                        help_text="One or two lines about the piece, for the card.",
                        max_length=300,
                    ),
                ),
                (
                    "teacher_note",
                    models.TextField(
                        blank=True,
                        help_text="What is simplified or left out, said plainly.",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Where the notes come from.", max_length=300
                    ),
                ),
                (
                    "authorship",
                    models.CharField(
                        choices=[
                            ("ai_drafted", "drafted by AI, not yet checked at the piano"),
                            ("reviewed", "drafted by AI, checked and corrected"),
                            ("avi_written", "written by Avi"),
                        ],
                        default="ai_drafted",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "order"), name="improv_piece_level_order_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PieceTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rung",
                    models.CharField(
                        help_text="A rung key of the piece's ladder, or drill for any bars.",
                        max_length=20,
                    ),
                ),
                (
                    "first_bar",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "last_bar",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "hands",
                    models.CharField(
                        choices=[("R", "right hand"), ("L", "left hand"), ("B", "both hands")],
                        max_length=1,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("flow", "flow: the pulse never waits"),
                            ("step", "step: it waits for the right note"),
                        ],
                        default="flow",
                        max_length=4,
                    ),
                ),
                (
                    "tempo_bpm",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                ("curtain", models.BooleanField(default=False)),
                (
                    "notes",
                    models.JSONField(
                        default=list,
                        help_text="The stretch as written: {hand, step, acc, midi, beat, dur, bar} per note, rebased to the stretch.",
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="{t_ms, type: on/off, note, velocity} as the MIDI arrived.",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        default=list,
                        help_text="The judge's word on each written note: {state, timing, offset_ms, played}.",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "pitch_accuracy",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "timing_accuracy",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("passed", models.BooleanField(default=False, editable=False)),
                (
                    "judge_version",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takes",
                        to="improv.piece",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_takes",
                        to="improv.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PiecePhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(help_text="1 for the first phrase.")),
                (
                    "first_bar",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "last_bar",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("title", models.CharField(max_length=60, validators=[improv.models._not_blank])),
                (
                    "hint",
                    models.CharField(
                        blank=True, help_text="Where each hand starts.", max_length=200
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phrases",
                        to="improv.piece",
                    ),
                ),
            ],
            options={
                "ordering": ["piece", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("piece", "order"), name="improv_piecephrase_order_unique"
                    )
                ],
            },
        ),
    ]
