# Generated by Django 5.2.12 on 2026-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notes/"),
        ),
    ]
