# Generated by Django 5.2.12 on 2026-05-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_video_infrastructure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="CopilotSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_username", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("invite_pending", "Invite Pending"),
                            ("active", "Active"),
                            ("expiring", "Expiring"),
                            ("revoked", "Revoked"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_seat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("assigned", "Assigned"),
                            ("revoked", "Revoked"),
                            ("reclaimed", "Reclaimed"),
                            ("warned", "Warned"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor", models.CharField(default="system", max_length=100)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("api_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.copilotseat",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
