# Generated by Django 5.2.12 on 2026-05-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_corporate_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("he", "Hebrew"), ("en", "English")], default="he", max_length=5
                    ),
                ),
                ("source_page", models.CharField(blank=True, max_length=200)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("utm_content", models.CharField(blank=True, max_length=100)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
