# Generated by Django 5.2.12 on 2026-05-25 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_newslettersubscriber"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("foundations", "Foundations"),
                    ("copilot", "Copilot"),
                    ("agents", "Agents"),
                    ("mcp", "MCP"),
                    ("prompting", "Prompting"),
                ],
                default="foundations",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="course",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="video",
            name="github_file",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="video",
            name="has_code_example",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="notes_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="video",
            name="summary_he",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="video",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="app.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
    ]
