# Generated by Django 5.2.12 on 2026-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_lesson_quiz_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservideoprogress",
            name="quiz_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lessonquiz",
            name="requires_correct",
            field=models.BooleanField(
                default=False,
                help_text="True → only correct answer unlocks Next. False → any answer unlocks Next.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
