# Generated by Django 5.2.12 on 2026-05-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_quiz_passed_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "material_type",
                    models.CharField(
                        choices=[("link", "קישור"), ("file", "קובץ")], default="link", max_length=10
                    ),
                ),
                ("url", models.URLField(blank=True, help_text="URL for link-type materials")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="File for file-type materials",
                        null=True,
                        upload_to="course_materials/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="app.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "חומר לימוד",
                "verbose_name_plural": "חומרי לימוד",
                "ordering": ["order", "title"],
            },
        ),
    ]
