# Generated by Django 5.2.15 on 2026-06-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.CharField(choices=[('matazim', 'מטצים'), ('ai', 'בינה מלאכותית'), ('innovation', 'הובלת חדשנות')], default='matazim', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
