# Generated by Django 5.2.15 on 2026-06-12 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_course_domain_course_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='reflection_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LessonReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default='')),
                ('user_text', models.TextField()),
                ('ai_reply', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='app.video')),
            ],
            options={
                'verbose_name': 'רפלקציה',
                'verbose_name_plural': 'רפלקציות',
                'ordering': ['-created_at'],
            },
        ),
    ]
