# Generated by Django 5.2.15 on 2026-06-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_video_reflection_prompt_lessonreflection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuthoringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(default='matazim', max_length=20)),
                ('track', models.CharField(blank=True, default='', max_length=40)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube URL'), ('upload', 'Uploaded file')], default='youtube', max_length=10)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='authoring_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('step', models.CharField(blank=True, default='', max_length=200)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_jobs', to='app.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authoring job',
                'ordering': ['-created_at'],
            },
        ),
    ]
