# Generated by Django 5.2.15 on 2026-06-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userprofile_is_author_authoringjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studio_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
