# Generated by Django 5.2.15 on 2026-06-12 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_course_studio_edited_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("interests", models.JSONField(blank=True, default=list)),
                ("goal", models.CharField(blank=True, default="", max_length=200)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("persona", models.CharField(blank=True, default="", max_length=200)),
                ("time_per_week", models.CharField(blank=True, default="", max_length=50)),
                ("recommended_track", models.CharField(blank=True, default="", max_length=50)),
                ("onboarding_completed_at", models.DateTimeField(blank=True, null=True)),
                ("onboarding_skipped_at", models.DateTimeField(blank=True, null=True)),
                ("source_entry_path", models.CharField(blank=True, default="", max_length=500)),
                ("source_entry_type", models.CharField(blank=True, default="", max_length=20)),
                ("source_course", models.CharField(blank=True, default="", max_length=200)),
                ("source_referrer", models.CharField(blank=True, default="", max_length=500)),
                ("source_utm", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.course",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
