# Generated by Django 5.2.15 on 2026-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_learnerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="learnerprofile",
            name="role_type",
            field=models.CharField(
                blank=True,
                choices=[("student", "Student"), ("teacher", "Teacher"), ("other", "Other")],
                default="",
                max_length=20,
            ),
        ),
    ]
