# Generated by Django 5.2.15 on 2026-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_arduino_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="learnerprofile",
            name="role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("professor", "Professor"),
                    ("industry_engineer", "Industry engineer"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
