# Generated by Django 5.2.15 on 2026-06-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_hackathon_challenge_hackrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "hardware_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("received", "Received"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("glory_consent", models.BooleanField(default=False)),
                ("anon_ordinal", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="app.hackathon",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="crashtech_teams", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("hackathon", "name")},
            },
        ),
    ]
