# Generated by Django 5.2.15 on 2026-06-13 19:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_qrtoken_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="GloryPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("highlights", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hackathon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glory_page",
                        to="app.hackathon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GloryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="crashtech/glory/")),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "glory_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="app.glorypage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("participation", "Participation"),
                            ("winner", "Winner"),
                            ("runner_up", "Runner-up"),
                        ],
                        default="participation",
                        max_length=14,
                    ),
                ),
                ("cert_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="app.hackathon",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="app.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("hackathon", "team")},
            },
        ),
    ]
