# Generated by Django 5.2.15 on 2026-06-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_channel_channelmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dms_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
