# Generated by Django 5.2.15 on 2026-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_eventseries_communityevent_eventphoto_eventrsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityevent",
            name="reminded_1h",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communityevent",
            name="reminded_24h",
            field=models.BooleanField(default=False),
        ),
    ]
