# Generated by Django 5.2.15 on 2026-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_communityevent_reminded_1h_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmessage",
            name="promoted_to",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
