# Generated by Django 5.2.15 on 2026-06-14 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_channelmessage_promoted_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rule_key", models.CharField(db_index=True, max_length=40)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("users_training", "Users & Training"),
                            ("costs", "Costs"),
                            ("engagement", "Engagement"),
                            ("system", "System"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("value", models.FloatField(default=0)),
                ("threshold", models.FloatField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("notified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("threshold", models.FloatField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("users_training", "Users & Training"),
                            ("costs", "Costs"),
                            ("engagement", "Engagement"),
                            ("system", "System"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service", models.CharField(db_index=True, max_length=40)),
                ("period", models.CharField(db_index=True, help_text="YYYY-MM", max_length=7)),
                ("amount_usd", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("live", "Live (API)"),
                            ("estimate", "Estimate (computed)"),
                            ("manual", "Manual (admin)"),
                        ],
                        default="estimate",
                        max_length=10,
                    ),
                ),
                ("deep_link", models.URLField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["service", "-period"],
                "indexes": [
                    models.Index(
                        fields=["service", "period"], name="app_costrec_service_74bc63_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("users_training", "Users & Training"),
                            ("costs", "Costs"),
                            ("engagement", "Engagement"),
                            ("system", "System"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "-captured_at"], name="app_dashboa_scope_9f3cff_idx"
                    )
                ],
            },
        ),
    ]
