# Generated by Django 5.2.15 on 2026-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alertevent_alertrule_costrecord_dashboardsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("recipients", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
