# Generated by Django 5.2.15 on 2026-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_emailsendlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="costrecord",
            name="admin_set",
            field=models.BooleanField(default=False),
        ),
    ]
