# Generated by Django 5.2.15 on 2026-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_tinkercad_project_cert"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="project_upload_type",
            field=models.CharField(
                choices=[("image", "Image / screenshot"), ("stl", "STL 3D model")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="model_file",
            field=models.FileField(blank=True, null=True, upload_to="project_models/"),
        ),
        migrations.AlterField(
            model_name="courseprojectsubmission",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_submissions/"),
        ),
    ]
