# Generated by Django 5.2.15 on 2026-06-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_fusion360_stl_cert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="accepts_model",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="LessonModelSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_file", models.FileField(upload_to="lesson_models/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_submissions",
                        to="app.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "הגשת דגם",
                "verbose_name_plural": "הגשות דגם",
                "ordering": ["video__lesson_order"],
                "unique_together": {("user", "video")},
            },
        ),
    ]
