# Generated by Django 5.2.15 on 2026-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_migrate_single_stl_to_lesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonmodelsubmission",
            options={
                "ordering": ["video__lesson_order"],
                "verbose_name": "הגשת פרויקט שיעור",
                "verbose_name_plural": "הגשות פרויקט שיעור",
            },
        ),
        migrations.AddField(
            model_name="lessonmodelsubmission",
            name="scratch_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="project_upload_type",
            field=models.CharField(
                choices=[
                    ("image", "Image / screenshot"),
                    ("stl", "STL 3D model"),
                    ("scratch", "Scratch project link"),
                ],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lessonmodelsubmission",
            name="model_file",
            field=models.FileField(blank=True, upload_to="lesson_models/"),
        ),
    ]
