# Generated by Django 5.2.15 on 2026-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_scratch_lesson4_simplify"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="project_min_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
