# Generated by Django 5.2.15 on 2026-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_rename_scratch_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cert_min_pct",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="lessonmodelsubmission",
            name="tinkercad_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="course",
            name="project_upload_type",
            field=models.CharField(
                choices=[
                    ("image", "Image / screenshot"),
                    ("stl", "STL 3D model"),
                    ("scratch", "Scratch project link"),
                    ("tinkercad", "Tinkercad project link"),
                ],
                default="image",
                max_length=12,
            ),
        ),
    ]
