# Generated by Django 5.2.15 on 2026-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_tinkercad_course_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonmodelsubmission",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="project_upload_type",
            field=models.CharField(
                choices=[
                    ("image", "Image / screenshot"),
                    ("stl", "STL 3D model"),
                    ("scratch", "Scratch project link"),
                    ("tinkercad", "Tinkercad project link"),
                    ("youtube", "YouTube video link"),
                ],
                default="image",
                max_length=12,
            ),
        ),
    ]
