# Generated by Django 5.2.15 on 2026-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_micropython_youtube_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="requires_completion",
            field=models.BooleanField(default=False),
        ),
    ]
