# Generated by Django 5.2.15 on 2026-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_classjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="courses_visibility",
            field=models.CharField(
                choices=[
                    ("certs", "תעודות בלבד"),
                    ("all", "כל הקורסים וההתקדמות"),
                    ("none", "להסתיר"),
                ],
                default="certs",
                max_length=5,
            ),
        ),
    ]
