# Generated by Django 5.2.15 on 2026-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_userprofile_courses_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
