# Generated by Django 5.2.15 on 2026-06-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_blogpost_blogimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGraderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4o", "GPT-4o · best quality"),
                            ("gpt-4o-mini", "GPT-4o-mini · cheapest"),
                        ],
                        default="gpt-4o",
                        max_length=20,
                    ),
                ),
                (
                    "image_detail",
                    models.CharField(
                        choices=[
                            ("high", "High · read fine detail"),
                            ("low", "Low · cheapest"),
                            ("auto", "Auto"),
                        ],
                        default="high",
                        max_length=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI grader config",
                "verbose_name_plural": "AI grader config",
            },
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="grade_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="grade_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="grade_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="graded_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="courseprojectsubmission",
            name="graded_model",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="usagelog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to="app.chatsession",
            ),
        ),
    ]
