# Generated by Django 5.2.15 on 2026-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_aigraderconfig_courseprojectsubmission_grade_ok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcode",
            name="passed",
            field=models.BooleanField(default=False),
        ),
    ]
