# Generated by Django 5.2.15 on 2026-06-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0079_python_lesson16_exercises_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="practice_required",
            field=models.BooleanField(default=False),
        ),
    ]
