# Generated by Django 5.2.15 on 2026-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_python_oop_lessons"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="feature_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
