# Generated by Django 5.2.15 on 2026-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0085_blogcomment_blogread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="courses_visibility",
            field=models.CharField(
                choices=[
                    ("certs", "תעודות בלבד"),
                    ("all", "כל ההדרכות וההתקדמות"),
                    ("none", "להסתיר"),
                ],
                default="certs",
                max_length=5,
            ),
        ),
    ]
