# Generated by Django 5.2.15 on 2026-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0090_enable_review_youtube_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reflections_public",
            field=models.BooleanField(default=True),
        ),
    ]
