# Generated by Django 5.2.15 on 2026-06-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_userprofile_reflections_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="issues_certificate",
            field=models.BooleanField(default=True),
        ),
    ]
