# Generated by Django 5.2.15 on 2026-06-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_course_issues_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='app.video'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='context_type',
            field=models.CharField(choices=[('course_tutor', 'Course Tutor'), ('lesson_tutor', 'Lesson Tutor'), ('code_helper', 'Code Helper'), ('general_assistant', 'General Assistant')], default='general_assistant', max_length=30),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='context_type',
            field=models.CharField(choices=[('course_tutor', 'Course Tutor'), ('lesson_tutor', 'Lesson Tutor'), ('code_helper', 'Code Helper'), ('general_assistant', 'General Assistant')], max_length=30, unique=True),
        ),
    ]
