# Generated by Django 5.2.15 on 2026-07-01 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_chatsession_video_alter_chatsession_context_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notebook_min_pass_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_notebooks',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotebookSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook_file', models.FileField(blank=True, upload_to='lesson_notebooks/')),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('graded_model', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_submissions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_submissions', to='app.video')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
