# Generated by Django 5.2.15 on 2026-08-08 14:38

import app.matazim_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_labsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("color_primary", models.CharField(default="#00d4a4", max_length=9)),
                ("color_ink", models.CharField(default="#585ba8", max_length=9)),
                ("color_surface", models.CharField(default="#e6e7f6", max_length=9)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="program_logos/")),
                (
                    "current_cohort_year",
                    models.PositiveIntegerField(default=app.matazim_models.current_year),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "תוכנית",
                "verbose_name_plural": "תוכניות",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("contact_name", models.CharField(blank=True, default="", max_length=150)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "בית ספר",
                "verbose_name_plural": "בתי ספר",
                "ordering": ["name"],
                "unique_together": {("program", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProgramMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cohort_year",
                    models.PositiveIntegerField(default=app.matazim_models.current_year),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "מתמיין"),
                            ("in_training", "לומד"),
                            ("project_submitted", "הגיש תוצר"),
                            ("certified", "מט״צ מוסמך"),
                            ("alumnus", "בוגר"),
                            ("rejected", "לא התקבל"),
                            ("revoked", "הסמכה בוטלה"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "מט״צ"),
                            ("school_leader", "מוביל בית ספר"),
                            ("program_staff", "צוות התוכנית"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("certification_note", models.TextField(blank=True, default="")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matazim_certifications_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="app.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="app.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "חברות בתוכנית",
                "verbose_name_plural": "חברויות בתוכנית",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "program", "cohort_year")},
            },
        ),
    ]
