# Generated by Django 5.2.15 on 2026-08-08 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_program_school_programmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmembership",
            name="role",
        ),
        migrations.AddField(
            model_name="program",
            name="staff",
            field=models.ManyToManyField(
                blank=True,
                related_name="programs_staffed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="צוות התוכנית",
            ),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="endorsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="endorsed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matazim_endorsements_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="endorsement_note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="school_join_status",
            field=models.CharField(
                choices=[("pending", "ממתין לאישור המוביל"), ("confirmed", "אושר")],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="schools_led",
                to=settings.AUTH_USER_MODEL,
                verbose_name="מובילי בית הספר",
            ),
        ),
        migrations.CreateModel(
            name="ProgramStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(blank=True, default="", max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matazim_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_log",
                        to="app.programmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "יומן שינויי סטטוס",
                "verbose_name_plural": "יומן שינויי סטטוס",
                "ordering": ["-created_at"],
            },
        ),
    ]
