# Generated by Django 5.2.15 on 2026-08-08 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0097_remove_programmembership_role_program_staff_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmembership",
            name="endorsed_at",
        ),
        migrations.RemoveField(
            model_name="programmembership",
            name="endorsed_by",
        ),
        migrations.RemoveField(
            model_name="programmembership",
            name="endorsement_note",
        ),
        migrations.AddField(
            model_name="programmembership",
            name="acceptance_note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matazim_acceptances_granted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
