# Generated by Django 5.2.15 on 2026-08-10 17:27

import django.db.models.deletion
from django.db import migrations, models

import app.classroom_models


def give_each_school_its_own_code(apps, schema_editor):
    """A column default is evaluated once, so adding a unique join_code straight
    off hands every existing school the *same* code and the constraint fails.
    Add it non-unique, fill it row by row, then make it unique."""
    School = apps.get_model("app", "School")
    for school in School.objects.all():
        School.objects.filter(pk=school.pk).update(
            join_code=app.classroom_models.gen_join_code())


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0098_remove_programmembership_endorsed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_open",
            field=models.BooleanField(default=True, verbose_name="פתוח להרשמה"),
        ),
        migrations.AddField(
            model_name="school",
            name="join_code",
            field=models.CharField(
                db_index=True,
                default=app.classroom_models.gen_join_code,
                max_length=24,
            ),
        ),
        migrations.RunPython(give_each_school_its_own_code,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name="school",
            name="join_code",
            field=models.CharField(
                db_index=True,
                default=app.classroom_models.gen_join_code,
                max_length=24,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ProgramApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, default="", max_length=40, verbose_name="כיתה"),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True, default="", verbose_name="למה אתם רוצים להיות מט״צים"
                    ),
                ),
                (
                    "built_before",
                    models.TextField(blank=True, default="", verbose_name="מה כבר בניתם"),
                ),
                ("via_invite_link", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="app.programmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "בקשת הצטרפות",
                "verbose_name_plural": "בקשות הצטרפות",
                "ordering": ["-created_at"],
            },
        ),
    ]
