# Generated by Django 5.2.15 on 2026-08-10 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0099_school_is_open_school_join_code_programapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntranceAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_id", models.CharField(max_length=16)),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "model_file",
                    models.FileField(blank=True, null=True, upload_to="entrance_tests/"),
                ),
                ("measured", models.JSONField(blank=True, default=dict)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("passed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrance_attempts",
                        to="app.programmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "ניסיון במבחן הכניסה",
                "verbose_name_plural": "ניסיונות במבחן הכניסה",
                "ordering": ["-created_at"],
                "unique_together": {("membership", "number")},
            },
        ),
    ]
