# Generated by Django 5.2.15 on 2026-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_entranceattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("ack_status", models.CharField(blank=True, max_length=16)),
                ("ack_detail", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ok", models.BooleanField(default=True)),
                ("cameras_online", models.IntegerField(default=0)),
                ("cameras_total", models.IntegerField(default=0)),
                ("last_event_ts", models.DateTimeField(blank=True, null=True)),
                ("disk_free_gb", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.CharField(max_length=254)),
                ("path", models.CharField(max_length=120)),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.BigIntegerField(db_index=True, unique=True)),
                ("ts", models.DateTimeField(db_index=True)),
                ("ts_raw", models.CharField(blank=True, max_length=64)),
                ("channel", models.CharField(max_length=32)),
                ("camera", models.CharField(db_index=True, max_length=120)),
                ("event_type", models.CharField(max_length=32)),
                ("severity", models.CharField(max_length=16)),
                ("names", models.JSONField(blank=True, default=list)),
                ("unidentified", models.IntegerField(default=0)),
                (
                    "incident_key",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                ("drive_url", models.URLField(blank=True, max_length=500, null=True)),
                ("drive_file_id", models.CharField(blank=True, max_length=128, null=True)),
                ("snapshot_path", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-ts", "-event_id"],
                "indexes": [
                    models.Index(fields=["-ts"], name="secev_ts_desc_idx"),
                    models.Index(fields=["camera", "-ts"], name="secev_cam_ts_idx"),
                ],
            },
        ),
    ]
