# Generated by Django 5.2.15 on 2026-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0101_securitycommand_securitystate_securityviewlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="alarm_state",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="armed",
            field=models.BooleanField(default=False),
        ),
    ]
