# Generated by Django 5.2.15 on 2026-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0102_securityevent_alarm_state_securityevent_armed"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="delete_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
