# Generated by Django 5.2.15 on 2026-09-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0103_securityevent_delete_requested_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityHighWater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_event_id", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
