# Generated by Django 5.2.15 on 2026-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0104_securityhighwater"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityResetDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                ("house_event_count", models.BigIntegerField(default=0)),
                ("our_event_count", models.BigIntegerField(default=0)),
                ("boundary_event_id", models.BigIntegerField(default=0)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("acted_by", models.CharField(blank=True, max_length=254)),
                ("deleted_count", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-declared_at"],
            },
        ),
    ]
