# Generated by Django 5.2.15 on 2026-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_security_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitystate',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
