# Generated by Django 5.2.15 on 2026-09-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_security_state_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitystate',
            name='alert_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitystate',
            name='alert_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
