# Generated by Django 5.2.15 on 2026-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_security_state_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='incident_cameras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='incident_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='incident_first_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='incident_last_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
