from django.contrib.auth import views as auth_views
from django.urls import path

from . import (
    chat_views,
    classroom_views,
    community_views,
    course_api,
    crashtech_views,
    dashboard_views,
    events_views,
    forum_views,
    onboarding_views,
    showcase_views,
    studio_views,
    tips_views,
    views,
)

urlpatterns = [
    path("", views.home, name="home"),
    path("add_note/", views.add_note, name="add_note"),
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    # Onboarding & first-time experience (EPIC-5)
    path("join/", onboarding_views.join_wall, name="join_wall"),
    path("welcome/", onboarding_views.welcome, name="welcome"),
    path("welcome/basics/", onboarding_views.welcome_basics, name="welcome_basics"),
    path("welcome/chat/", onboarding_views.welcome_chat, name="welcome_chat"),
    path("welcome/complete/", onboarding_views.welcome_complete, name="welcome_complete"),
    path("welcome/skip/", onboarding_views.welcome_skip, name="welcome_skip"),
    path("cookie-consent/", views.cookie_consent, name="cookie_consent"),
    path("verify-email/", views.verify_email, name="verify_email"),
    path("resend-verification/", views.resend_verification, name="resend_verification"),
    path("profile/", views.profile, name="profile"),
    path("search/", views.global_search, name="global_search"),
    path("search/json/", views.global_search_json, name="global_search_json"),
    path("account/delete/", views.delete_account, name="delete_account"),
    # --- Teachers & Classes / Classrooms (Chapter 9) ---
    path("classes/", classroom_views.my_classes, name="my_classes"),
    path("classes/all/", classroom_views.class_directory, name="class_directory"),
    path("classes/search/", classroom_views.class_search, name="class_search"),
    path("classes/become-teacher/", classroom_views.become_teacher, name="become_teacher"),
    path("classes/new/", classroom_views.class_create, name="class_create"),
    path("class/<int:pk>/request-join/", classroom_views.class_request_join, name="class_request_join"),
    path("class/request/<int:req_id>/approve/", classroom_views.class_request_approve, name="class_request_approve"),
    path("class/request/<int:req_id>/decline/", classroom_views.class_request_decline, name="class_request_decline"),
    path("class/join/<str:code>/", classroom_views.class_join, name="class_join"),
    path("class/invite/<int:invite_id>/respond/", classroom_views.invite_respond, name="invite_respond"),
    path("class/<int:pk>/", classroom_views.classroom, name="classroom"),
    path("class/<int:pk>/manage/", classroom_views.class_manage, name="class_manage"),
    path("class/<int:pk>/qr.png", classroom_views.class_qr, name="class_qr"),
    path("class/<int:pk>/search-users/", classroom_views.class_user_search, name="class_user_search"),
    path("class/<int:pk>/invite/", classroom_views.class_invite, name="class_invite"),
    path("class/invite/<int:invite_id>/resend/", classroom_views.class_invite_resend, name="class_invite_resend"),
    path("class/<int:pk>/post/", classroom_views.class_post, name="class_post"),
    path("class/<int:pk>/toggle-share/", classroom_views.class_toggle_share, name="class_toggle_share"),
    path("class/<int:pk>/leave/", classroom_views.class_leave, name="class_leave"),
    path("class/<int:pk>/toggle-open/", classroom_views.class_toggle_open, name="class_toggle_open"),
    path("class/<int:pk>/rotate-code/", classroom_views.class_rotate_code, name="class_rotate_code"),
    path("class/<int:pk>/delete/", classroom_views.class_delete, name="class_delete"),
    path("class/<int:pk>/remove/<int:student_id>/", classroom_views.class_remove, name="class_remove"),
    path("class/<int:pk>/student/<int:student_id>/", classroom_views.class_student, name="class_student"),
    path("staff/copilot-dashboard/", views.CopilotDashboardView.as_view(), name="copilot_dashboard"),
    # --- Admin / Management Control Dashboard (EPIC-8) - superuser only ---
    path("admin-dashboard/", dashboard_views.admin_dashboard, name="admin_dashboard"),
    path("admin-dashboard/refresh/<str:section>/", dashboard_views.refresh_section, name="dashboard_refresh"),
    path("admin-dashboard/cost/manual/", dashboard_views.manual_cost, name="dashboard_manual_cost"),
    path("admin-dashboard/alerts/config/", dashboard_views.alert_config, name="dashboard_alert_config"),
    path("admin-dashboard/grader/config/", dashboard_views.grader_config, name="dashboard_grader_config"),
    path("admin-dashboard/alerts/<int:pk>/dismiss/", dashboard_views.dismiss_alert, name="dashboard_dismiss_alert"),
    # Machine endpoint: weekly GitHub Actions cron POSTs here with X-Backup-Token
    # to run an in-process backup (REQ-1.2.4).
    path("internal/run-backup/", dashboard_views.run_backup, name="run_backup"),
    # Machine endpoint: daily GitHub Actions cron POSTs here with X-Capture-Token
    # to refresh all dashboard data in-process (REQ-8.1.4).
    path("internal/run-capture/", dashboard_views.run_dashboard_capture, name="run_dashboard_capture"),
    # Machine endpoint (token): send a test alert email to all superusers.
    path("internal/test-alert-email/", dashboard_views.test_alert_email, name="test_alert_email"),

    # --- Community (EPIC-6.1) ---
    path("community/", community_views.community_home, name="community"),
    path("community/guidelines/", community_views.guidelines, name="community_guidelines"),
    path("community/leaderboard/", community_views.leaderboard, name="community_leaderboard"),
    path("community/notifications/", community_views.notifications_page, name="community_notifications"),
    path("community/members/", community_views.members_directory, name="community_members"),
    path("staff/community-health/", community_views.community_health, name="community_health"),
    path("community/settings/", community_views.community_settings_save, name="community_settings"),
    path("community/join/", community_views.community_go_public, name="community_go_public"),
    path("community/report/", community_views.report_content, name="community_report"),
    path("c/<str:username>/", community_views.public_profile, name="community_profile"),
    path("c/<str:username>/follow/", community_views.follow_toggle, name="community_follow"),
    path("c/<str:username>/activity/", community_views.user_activity, name="user_activity"),
    # --- Events & Meetups (EPIC-6.7) ---
    path("community/events/", events_views.events_page, name="events_page"),
    path("community/events/new/", events_views.event_create, name="event_create"),
    path("community/events/series/<slug:slug>/", events_views.series_page, name="event_series"),
    path("community/events/<slug:slug>/", events_views.event_detail, name="event_detail"),
    path("community/events/<slug:slug>/rsvp/", events_views.event_rsvp, name="event_rsvp"),
    path("community/events/<slug:slug>/cancel/", events_views.event_cancel, name="event_cancel"),
    path("community/events/<slug:slug>/edit/", events_views.event_edit, name="event_edit"),
    path("community/events/<slug:slug>/checkin/", events_views.event_checkin, name="event_checkin"),
    path("community/events/<slug:slug>/photo/", events_views.event_photo, name="event_photo"),
    path("community/events/<slug:slug>/calendar.ics", events_views.event_ics, name="event_ics"),
    # --- Chat & Groups (EPIC-6.6) ---
    path("community/chat/", chat_views.chat_home, name="chat_home"),
    path("community/chat/course/<slug:slug>/", chat_views.course_channel, name="course_channel"),
    path("community/chat/<slug:slug>/", chat_views.channel_view, name="channel_view"),
    path("community/chat/<slug:slug>/messages/", chat_views.channel_messages_api, name="channel_messages"),
    path("community/chat/message/<int:message_id>/promote/", chat_views.promote_message, name="promote_message"),
    path("community/chat/message/<int:message_id>/report/", chat_views.report_message, name="report_message"),
    path("community/chat/message/<int:message_id>/hide/", chat_views.hide_message, name="hide_message"),
    # --- Tips & Feed (EPIC-6.4) ---
    path("community/tips/", tips_views.tips_list, name="tips_list"),
    path("community/tips/new/", tips_views.tip_create, name="tip_create"),
    path("community/tips/<int:tip_id>/", tips_views.tip_detail, name="tip_detail"),
    path("community/tips/<int:tip_id>/react/", tips_views.tip_react, name="tip_react"),
    # --- Forums & Q&A (EPIC-6.2) ---
    path("community/forum/", forum_views.forum_home, name="forum_home"),
    path("community/forum/new/", forum_views.thread_new, name="forum_new"),
    path("community/forum/similar/", forum_views.similar_threads, name="forum_similar"),
    path("community/forum/preview/", forum_views.forum_preview, name="forum_preview"),
    path("community/forum/thread/<int:thread_id>/", forum_views.thread_detail, name="forum_thread"),
    path("community/forum/thread/<int:thread_id>/answer/", forum_views.post_answer, name="forum_answer"),
    path("community/forum/thread/<int:thread_id>/subscribe/", forum_views.subscribe_thread, name="forum_subscribe"),
    path("community/forum/thread/<int:thread_id>/curate/", forum_views.thread_curate, name="forum_curate"),
    path("community/forum/thread/<int:thread_id>/summarize/", forum_views.summarize_thread, name="forum_summarize"),
    path("community/forum/thread/<int:thread_id>/draft/", forum_views.draft_answer, name="forum_draft"),
    path("community/forum/post/<int:post_id>/vote/", forum_views.vote_post, name="forum_vote"),
    path("community/forum/post/<int:post_id>/accept/", forum_views.accept_answer, name="forum_accept"),
    # --- Showcase / דוכן השוויץ (EPIC-6.3) ---
    path("community/showcase/", showcase_views.showcase_wall, name="showcase_wall"),
    path("community/showcase/feed/", showcase_views.showcase_feed, name="showcase_feed"),
    path("community/showcase/new/", showcase_views.project_create, name="showcase_new"),
    path("community/showcase/stand/<slug:stand>/", showcase_views.showcase_wall, name="showcase_stand"),
    path("community/showcase/p/<int:project_id>/", showcase_views.project_detail, name="showcase_project"),
    path("community/showcase/p/<int:project_id>/edit/", showcase_views.project_edit, name="showcase_edit"),
    path("community/showcase/p/<int:project_id>/delete/", showcase_views.project_delete, name="showcase_delete"),
    path("community/showcase/p/<int:project_id>/react/", showcase_views.project_react, name="showcase_react"),
    path("community/showcase/p/<int:project_id>/comment/", showcase_views.project_comment, name="showcase_comment"),
    path("community/showcase/p/<int:project_id>/feature/", showcase_views.project_feature, name="showcase_feature"),
    # --- Direct messages (EPIC-6.3, REQ-6.3.12) ---
    path("community/messages/", community_views.messages_inbox, name="messages_inbox"),
    path("community/messages/<str:username>/", community_views.message_thread, name="messages_thread"),
    path("community/messages/<str:username>/block/", community_views.message_block, name="messages_block"),

    # --- CrashTech: hackathon platform (EPIC-6.5) ---
    path("crashtech/", crashtech_views.crashtech_home, name="crashtech_home"),
    path("crashtech/new/", crashtech_views.hackathon_create, name="crashtech_create"),
    path("crashtech/<slug:slug>/", crashtech_views.hackathon_detail, name="crashtech_detail"),
    path("crashtech/<slug:slug>/manage/", crashtech_views.hackathon_manage, name="crashtech_manage"),
    path("crashtech/<slug:slug>/edit/", crashtech_views.hackathon_edit, name="crashtech_edit"),
    path("crashtech/<slug:slug>/challenges/new/", crashtech_views.challenge_create, name="crashtech_challenge_new"),
    path("crashtech/<slug:slug>/challenges/<int:challenge_id>/edit/", crashtech_views.challenge_edit, name="crashtech_challenge_edit"),
    path("crashtech/<slug:slug>/challenges/<int:challenge_id>/delete/", crashtech_views.challenge_delete, name="crashtech_challenge_delete"),
    path("crashtech/<slug:slug>/judges/", crashtech_views.judge_assign, name="crashtech_judges"),
    path("crashtech/<slug:slug>/participants/", crashtech_views.participants, name="crashtech_participants"),
    path("crashtech/<slug:slug>/teams/", crashtech_views.teams, name="crashtech_teams"),
    path("crashtech/<slug:slug>/teams/create/", crashtech_views.participant_create_team, name="crashtech_team_create"),
    path("crashtech/<slug:slug>/teams/<int:team_id>/join/", crashtech_views.participant_join_team, name="crashtech_team_join"),
    path("crashtech/<slug:slug>/teams/<int:team_id>/", crashtech_views.team_edit, name="crashtech_team_edit"),
    path("crashtech/<slug:slug>/hardware/", crashtech_views.hardware_inventory, name="crashtech_hardware"),
    path("crashtech/<slug:slug>/challenges/<int:challenge_id>/submit/", crashtech_views.submit_solution, name="crashtech_submit"),
    path("crashtech/<slug:slug>/challenges/<int:challenge_id>/qr/", crashtech_views.challenge_qr, name="crashtech_qr"),
    path("crashtech/u/<str:token>/", crashtech_views.qr_upload, name="crashtech_qr_upload"),
    path("crashtech/<slug:slug>/judge/", crashtech_views.judge_queue, name="crashtech_judge"),
    path("crashtech/<slug:slug>/submissions/<int:submission_id>/review/", crashtech_views.review_submission, name="crashtech_review"),
    path("crashtech/<slug:slug>/challenges/<int:challenge_id>/bonus/", crashtech_views.bonus_award, name="crashtech_bonus"),
    path("crashtech/<slug:slug>/leaderboard/", crashtech_views.leaderboard, name="crashtech_leaderboard"),
    path("crashtech/<slug:slug>/certificates/", crashtech_views.generate_certificates, name="crashtech_certificates"),
    path("crashtech/cert/<uuid:cert_id>/", crashtech_views.certificate_view, name="crashtech_certificate"),
    path("crashtech/<slug:slug>/glory/", crashtech_views.glory_page, name="crashtech_glory"),
    path("crashtech/<slug:slug>/glory/edit/", crashtech_views.glory_edit, name="crashtech_glory_edit"),
    path("crashtech/<slug:slug>/consent/", crashtech_views.consent_toggle, name="crashtech_consent"),
    path("crashtech/<slug:slug>/gallery/", crashtech_views.video_gallery, name="crashtech_gallery"),

    # Apex section placeholders (coming soon)
    path("services/", views.coming_soon, {"section": "services"}, name="services"),
    path("workshops/", views.coming_soon, {"section": "workshops"}, name="workshops"),
    path("nostalgia/", views.coming_soon, {"section": "nostalgia"}, name="nostalgia"),
    path("research/", views.coming_soon, {"section": "research"}, name="research"),
    # Avi Salmon Blog (personal). <str:> (not <slug:>) so unicode/Hebrew slugs match.
    path("blog/", views.blog_index, name="blog"),
    path("blog/<str:slug>/comment/", views.blog_comment, name="blog_comment"),
    path("blog/<str:slug>/", views.blog_post, name="blog_post"),
    path("newsletter/signup/", views.newsletter_signup, name="newsletter_signup"),
    path("newsletter/confirm/<str:token>", views.newsletter_confirm, name="newsletter_confirm"),
    # Courses (plural - SPR-2.2)
    path("courses/", views.courses_catalog, name="courses_catalog"),
    path("courses/search/", views.courses_search, name="courses_search"),
    path("courses/topic/<slug:domain>/", views.courses_domain, name="courses_domain"),
    path("courses/topic/<slug:domain>/<slug:track>/", views.courses_track, name="courses_track"),
    path("courses/<slug:slug>/", views.courses_detail, name="courses_detail"),
    path("courses/<slug:slug>/enroll/", views.courses_enroll, name="courses_enroll"),
    path("courses/<slug:slug>/finish/", views.course_finish, name="course_finish"),
    path("courses/<slug:slug>/review/<int:user_id>/", views.course_review, name="course_review"),
    path("courses/<slug:slug>/submit-project/", views.course_submit_project, name="course_submit_project"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/submit-model/", views.lesson_submit_model, name="lesson_submit_model"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/submit-scratch/", views.lesson_submit_scratch, name="lesson_submit_scratch"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/submit-tinkercad/", views.lesson_submit_tinkercad, name="lesson_submit_tinkercad"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/submit-youtube/", views.lesson_submit_youtube, name="lesson_submit_youtube"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/code/save/", views.lesson_code_save, name="lesson_code_save"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/code/coach/", views.lesson_code_coach, name="lesson_code_coach"),
    path("courses/<slug:slug>/lesson/<int:lesson_order>/", views.courses_lesson, name="courses_lesson"),
    # Courses (singular - SPR-1.4/1.5 entitlement-gated)
    path("course/<slug:slug>/", views.course_detail_view, name="course_detail"),
    path("course/<slug:slug>/lesson/<int:lesson_order>/", views.lesson_view, name="lesson_view"),
    # Certificate
    path("certificate/<uuid:cert_id>/", views.certificate_view, name="certificate_view"),
    path("certificate/<uuid:cert_id>/image.png", views.certificate_image, name="certificate_image"),
    path("model-submission/<int:pk>/download", views.lesson_model_download, name="lesson_model_download"),
    # Video progress heartbeat (SPR-1.4)
    path("api/video-progress/", views.video_progress_heartbeat, name="video_progress"),
    path("api/lesson/<int:video_id>/reflect/", views.lesson_reflect, name="lesson_reflect"),
    # Legacy heartbeat alias (used by lesson.html prev/next)
    path("courses/<slug:slug>/heartbeat/", views.video_progress_heartbeat, name="video_heartbeat"),
    # AI Chat (SPR-1.8)
    path("chat/", views.chat_page, name="chat_page"),
    path("api/chat/", views.chat_api, name="chat_api"),
    path("api/chat/sessions/", views.chat_sessions_api, name="chat_sessions_api"),
    path("staff/ai-usage/", views.AiUsageDashboardView.as_view(), name="ai_usage_dashboard"),

    # Course Management API (SPR-2.3)
    # --- Authoring Studio (EPIC-4) ---
    path("studio/", studio_views.studio_home, name="studio_home"),
    path("studio/course/new/", studio_views.course_create, name="studio_course_create"),
    path("studio/new-from-video/", studio_views.new_from_video, name="studio_new_from_video"),
    path("studio/preview/", studio_views.markdown_preview, name="studio_markdown_preview"),
    path("studio/job/<int:job_id>/", studio_views.job_status, name="studio_job"),
    path("studio/job/<int:job_id>/status/", studio_views.job_status_api, name="studio_job_api"),
    path("studio/course/<slug:slug>/", studio_views.course_edit, name="studio_course_edit"),
    path("studio/course/<slug:slug>/delete/", studio_views.course_delete, name="studio_course_delete"),
    path("studio/course/<slug:slug>/publish/", studio_views.course_publish, name="studio_course_publish"),
    path("studio/course/<slug:slug>/reorder/", studio_views.lesson_reorder, name="studio_lesson_reorder"),
    path("studio/course/<slug:slug>/lesson/new/", studio_views.lesson_edit, name="studio_lesson_new"),
    path("studio/course/<slug:slug>/lesson/<int:order>/", studio_views.lesson_edit, name="studio_lesson_edit"),
    path("studio/course/<slug:slug>/lesson/<int:order>/delete/", studio_views.lesson_delete, name="studio_lesson_delete"),

    path("api/v1/courses/", course_api.list_courses, name="api_courses_list"),
    path("api/v1/courses/sync/", course_api.sync_course, name="api_courses_sync"),
    path("api/v1/courses/<slug:slug>/", course_api.course_detail, name="api_courses_detail"),
    path("api/v1/media/upload/", course_api.upload_media, name="api_media_upload"),
]
