# Generated by Django 5.2.15 on 2026-09-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0002_family_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route_summary",
            field=models.CharField(
                blank=True,
                help_text='e.g. "NYC → Finger Lakes → Niagara Falls → ... → home"',
                max_length=300,
            ),
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("return", "Return")], max_length=10
                    ),
                ),
                ("flight_number", models.CharField(blank=True, max_length=20)),
                (
                    "departure_label",
                    models.CharField(
                        blank=True,
                        help_text='Free text, e.g. "EWR 15:25 2026-10-01"',
                        max_length=120,
                    ),
                ),
                (
                    "arrival_label",
                    models.CharField(
                        blank=True,
                        help_text='Free text, e.g. "Newark (EWR) ~15:50"',
                        max_length=120,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="ustrip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RentalCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("pickup_location", models.CharField(blank=True, max_length=200)),
                ("dropoff_date", models.DateField(blank=True, null=True)),
                ("dropoff_location", models.CharField(blank=True, max_length=200)),
                ("vehicle_class", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField(blank=True)),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, help_text="Actually booked, not just researched."
                    ),
                ),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_car",
                        to="ustrip.trip",
                    ),
                ),
            ],
        ),
    ]
