# Generated by Django 5.2.15 on 2026-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0003_trip_route_summary_flight_rentalcar"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryday",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="An open decision or a heads-up for the whole day, not tied to one timeline item.",
            ),
        ),
    ]
