# Generated by Django 5.2.15 on 2026-09-14 04:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0004_itineraryday_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryday",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Where the day's schedule starts counting from.",
            ),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="booking",
            field=models.CharField(
                choices=[
                    ("not_needed", "No booking needed"),
                    ("to_book", "Needs booking"),
                    ("booked", "Booked"),
                ],
                default="not_needed",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="cost",
            field=models.CharField(
                blank=True, default="", help_text="Free text, e.g. '~$42/person'.", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="enriched_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Set once by enrich_ustrip_items. Explicit state, so a redeploy can never mistake an item a family member has since edited for one still in its seeded shape.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="fixed_start",
            field=models.TimeField(
                blank=True,
                help_text="Pin to a fixed time (a flight, a timed ticket). Everything after flows from it.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="tips",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short headline, e.g. 'Top of the Rock'.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="tag",
            field=models.CharField(
                choices=[("plan", "Plan"), ("optional", "Optional"), ("rejected", "Rejected")],
                default="plan",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="time_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional note shown next to the time.",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="ItineraryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ustrip.itineraryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("url", models.URLField(max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "Official site"),
                            ("wikipedia", "Wikipedia"),
                            ("map", "Map"),
                            ("tickets", "Tickets"),
                            ("other", "Other"),
                        ],
                        default="official",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="ustrip.itineraryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("photo", models.ImageField(upload_to="ustrip/items/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="ustrip.itineraryitem",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="ustrip.itineraryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "user"), name="one_like_per_user_per_item"
                    )
                ],
            },
        ),
    ]
