# Generated by Django 5.2.15 on 2026-09-14 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0005_item_schedule_links_photos_likes_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryday",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(23, 0),
                help_text="When the day is meant to be over. Nothing is refused past it; items that run later are flagged.",
            ),
        ),
    ]
