# Generated by Django 5.2.15 on 2026-09-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0006_itineraryday_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryday",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="The calendar day (first one, for a row that spans two).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itineraryday",
            name="date_end",
            field=models.DateField(
                blank=True,
                help_text="Last calendar day of the row; same as `date` for one day.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="timezone",
            field=models.CharField(
                default="America/New_York",
                help_text="Where the trip happens. 'Today' and 'now' are read on this clock, not the server's.",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="Lodging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Hotel name, once there is one.", max_length=200
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address or just the town, for the map link.",
                        max_length=300,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, help_text="Actually booked, not just planned."
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Confirmation number, parking, breakfast — whatever matters.",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lodgings",
                        to="ustrip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["check_in", "id"],
            },
        ),
        migrations.CreateModel(
            name="TripNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="ustrip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
