# Generated by Django 5.2.15 on 2026-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0007_trip_timezone_day_dates_lodging_tripnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitem",
            name="kind",
            field=models.CharField(
                choices=[("stop", "Stop (scheduled)"), ("note", "Note (no time)")],
                default="stop",
                help_text="A note is a reminder or a piece of information placed in the day's order: no time, and it never moves the times around it (Avi, 2026-09-14).",
                max_length=6,
            ),
        ),
    ]
