# Generated by Django 5.2.15 on 2026-09-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ustrip", "0008_itineraryitem_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryphoto",
            name="content_type",
            field=models.CharField(blank=True, default="image/jpeg", max_length=64),
        ),
        migrations.AddField(
            model_name="itineraryphoto",
            name="drive_file_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="itineraryphoto",
            name="drive_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="journalpost",
            name="content_type",
            field=models.CharField(blank=True, default="image/jpeg", max_length=64),
        ),
        migrations.AddField(
            model_name="journalpost",
            name="drive_file_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="journalpost",
            name="drive_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="itineraryphoto",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="ustrip/items/"),
        ),
    ]
