# Generated by Django 5.2.15 on 2026-09-10 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entered_via_matazim",
                    models.BooleanField(default=False, verbose_name="נכנס דרך מט״צים"),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "welcome_accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="אישר את הודעת אב הטיפוס"
                    ),
                ),
                (
                    "entrance_test_passed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="עבר את מבחן הכניסה"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "פרופיל מט״צים",
                "verbose_name_plural": "פרופילי מט״צים",
            },
        ),
    ]
