# Generated by Django 5.2.15 on 2026-09-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntranceTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_id", models.CharField(db_index=True, max_length=16, unique=True)),
                ("shape", models.CharField(max_length=40)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("brief", models.TextField(blank=True, default="")),
                ("is_retired", models.BooleanField(default=False, verbose_name="הוצא משימוש")),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "משימת מבחן כניסה",
                "verbose_name_plural": "משימות מבחן כניסה",
                "ordering": ["target_id"],
            },
        ),
        migrations.CreateModel(
            name="EntranceAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_id", models.CharField(max_length=16)),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "model_file",
                    models.FileField(blank=True, null=True, upload_to="matazim_entrance/"),
                ),
                ("measured", models.JSONField(blank=True, default=dict)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("passed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="matazim.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ניסיון מבחן כניסה",
                "verbose_name_plural": "ניסיונות מבחן כניסה",
                "ordering": ["number"],
                "unique_together": {("member", "number")},
            },
        ),
    ]
