# Generated by Django 5.2.15 on 2026-09-10 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import matazim.models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0002_entrancetarget_entranceattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="מנהל/ת התוכנית"),
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("contact", models.CharField(blank=True, default="", max_length=200)),
                (
                    "join_code",
                    models.CharField(
                        db_index=True,
                        default=matazim.models.new_join_code,
                        max_length=32,
                        unique=True,
                        verbose_name="קוד הצטרפות",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_leader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "מוביל",
                "verbose_name_plural": "מובילים",
            },
        ),
        migrations.CreateModel(
            name="StudyClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="שם הכיתה")),
                (
                    "school_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="בית ספר"
                    ),
                ),
                ("year", models.PositiveIntegerField(default=matazim.models.current_year)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="matazim.leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "כיתה",
                "verbose_name_plural": "כיתות",
                "ordering": ["school_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "מתמיינים"),
                            ("in_training", "לומדים"),
                            ("project_submitted", "יוצרים"),
                            ("certified", "מדריכים"),
                            ("alumnus", "משפיעים"),
                            ("rejected", "לא התקבל"),
                            ("revoked", "הוסר"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("cohort_year", models.PositiveIntegerField(default=matazim.models.current_year)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="matazim.leader",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="students", to="matazim.studyclass"
                    ),
                ),
            ],
            options={
                "verbose_name": "מט״צ",
                "verbose_name_plural": "מט״צים",
                "ordering": ["-cohort_year", "user__email"],
                "unique_together": {("user", "cohort_year")},
            },
        ),
    ]
