# Generated by Django 5.2.15 on 2026-09-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0003_memberprofile_is_admin_leader_studyclass_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pending_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="matazim.leader",
                verbose_name="ממתין לאישור של",
            ),
        ),
    ]
