# Generated by Django 5.2.15 on 2026-09-11 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0004_student_pending_leader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="certified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="הוסמך בתאריך"),
        ),
        migrations.AddField(
            model_name="student",
            name="certified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matazim_certified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="הוסמך על ידי",
            ),
        ),
    ]
