# Generated by Django 5.2.15 on 2026-09-11 08:48

from django.db import migrations, models

import matazim.storage


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0005_student_certified_at_student_certified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entranceattempt",
            name="model_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=matazim.storage.PrivateStorage(),
                upload_to=matazim.storage.entrance_upload_path,
            ),
        ),
    ]
