# Generated by Django 5.2.15 on 2026-09-11 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0007_move_uploads_out_of_public_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="birth_year",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="שנת לידה"),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="guardian_consent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="הסכמת הורה התקבלה"),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="guardian_consent_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ההסכמה נרשמה על ידי",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="guardian_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="אימייל של ההורה"
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="guardian_name",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="הורה/אפוטרופוס"
            ),
        ),
    ]
