# Generated by Django 5.2.15 on 2026-09-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0008_memberprofile_birth_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ran_at", models.DateTimeField(auto_now_add=True, verbose_name="בוצע בתאריך")),
                (
                    "deleted_count",
                    models.PositiveIntegerField(default=0, verbose_name="רשומות שנמחקו"),
                ),
                ("kind", models.CharField(default="failed_attempts", max_length=40)),
                (
                    "ran_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="אושר על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "ניקוי מידע ישן",
                "verbose_name_plural": "ניקויי מידע ישן",
                "ordering": ["-ran_at"],
            },
        ),
    ]
