# Generated by Django 5.2.15 on 2026-09-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0010_rename_is_admin_to_is_program_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leader",
            name="program_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matazim_leaders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="מנהל/ת התוכנית",
            ),
        ),
    ]
