# Generated by Django 5.2.15 on 2026-09-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import matazim.models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0012_backfill_leader_program_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("personal", "אישית"), ("open", "פתוחה")],
                        default="personal",
                        max_length=12,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=matazim.models.new_invite_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="עבור"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="אימייל"
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "הזמנת מוביל/ה",
                "verbose_name_plural": "הזמנות מובילים",
                "ordering": ["-created_at"],
            },
        ),
    ]
