# Generated by Django 5.2.15 on 2026-09-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0013_leader_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leader",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="אושר/ה בתאריך"),
        ),
        migrations.AddField(
            model_name="leader",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="אושר/ה על ידי",
            ),
        ),
    ]
