# Generated by Django 5.2.15 on 2026-09-11 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0015_backfill_leader_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="משלב"),
                ),
                ("to_status", models.CharField(max_length=20, verbose_name="לשלב")),
                (
                    "note",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="הערה"),
                ),
                ("at", models.DateTimeField(auto_now_add=True, verbose_name="מתי")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="על ידי",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="matazim.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "שינוי שלב",
                "verbose_name_plural": "שינויי שלב",
                "ordering": ["-at"],
            },
        ),
    ]
