# Generated by Django 5.2.15 on 2026-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0016_status_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applied", "מתמיינים"),
                    ("in_training", "לומדים"),
                    ("project_submitted", "יוצרים"),
                    ("certified", "מדריכים"),
                    ("alumnus", "משפיעים"),
                    ("rejected", "לא התקבל"),
                    ("revoked", "הוסר"),
                ],
                default="",
                max_length=20,
                verbose_name="משלב",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("applied", "מתמיינים"),
                    ("in_training", "לומדים"),
                    ("project_submitted", "יוצרים"),
                    ("certified", "מדריכים"),
                    ("alumnus", "משפיעים"),
                    ("rejected", "לא התקבל"),
                    ("revoked", "הוסר"),
                ],
                max_length=20,
                verbose_name="לשלב",
            ),
        ),
    ]
