# Generated by Django 5.2.15 on 2026-09-12 04:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0017_status_log_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatazCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                (
                    "name_on_certificate",
                    models.CharField(max_length=200, verbose_name="השם על התעודה"),
                ),
                (
                    "awarded_by_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="הוסמך על ידי"
                    ),
                ),
                ("awarded_at", models.DateTimeField(verbose_name="תאריך ההסמכה")),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="בוטלה בתאריך"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="matazim.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "תעודת מט״צ",
                "verbose_name_plural": "תעודות מט״צ",
            },
        ),
    ]
