# Generated by Django 5.2.15 on 2026-09-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0018_mataz_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, default="", max_length=40, verbose_name="כיתה"),
                ),
                (
                    "motivation",
                    models.TextField(blank=True, default="", verbose_name="מה מושך אותם לתוכנית"),
                ),
                (
                    "built_before",
                    models.TextField(blank=True, default="", verbose_name="מה כבר בנו"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "asked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="matazim.leader",
                        verbose_name="הבקשה הופנתה אל",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="matazim.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "בקשת הצטרפות",
                "verbose_name_plural": "בקשות הצטרפות",
                "ordering": ["-created_at"],
            },
        ),
    ]
