# Generated by Django 5.2.15 on 2026-09-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0019_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="from_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matazim.leader",
                verbose_name="ממוביל/ה",
            ),
        ),
        migrations.AddField(
            model_name="statuslog",
            name="to_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matazim.leader",
                verbose_name="למוביל/ה",
            ),
        ),
    ]
