# Generated by Django 5.2.15 on 2026-09-12 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0020_statuslog_from_leader_statuslog_to_leader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("author_role", models.CharField(blank=True, default="", max_length=40)),
                ("body", models.TextField(verbose_name="הבקשה")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("idea", "רעיון לשיפור"),
                            ("problem", "משהו לא עובד או מבלבל"),
                            ("copy", "נוסח או מילה"),
                            ("question", "שאלה"),
                        ],
                        default="idea",
                        max_length=20,
                        verbose_name="סוג",
                    ),
                ),
                (
                    "from_screen",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="נשלח מהמסך"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "חדשה"),
                            ("approved", "אושרה"),
                            ("declined", "לא מתאימה כרגע"),
                            ("done", "בוצעה"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="מצב",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="הוכרע בתאריך"),
                ),
                ("assessment", models.TextField(blank=True, default="", verbose_name="הערכה")),
                ("assessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sprint",
                    models.CharField(blank=True, default="", max_length=40, verbose_name="ספרינט"),
                ),
                ("outcome", models.TextField(blank=True, default="", verbose_name="מה נעשה")),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("summary_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נכתב על ידי",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="הוכרע על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "בקשה",
                "verbose_name_plural": "בקשות",
                "ordering": ["-created_at"],
            },
        ),
    ]
