# Generated by Django 5.2.15 on 2026-09-13 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0021_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="recommendation",
            field=models.TextField(blank=True, default="", verbose_name="המלצה"),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "טיוטה"),
                    ("new", "חדשה"),
                    ("approved", "אושרה"),
                    ("declined", "לא מתאימה כרגע"),
                    ("done", "בוצעה"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="מצב",
            ),
        ),
        migrations.CreateModel(
            name="RequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        choices=[("person", "המבקש/ת"), ("assistant", "העוזר")],
                        max_length=20,
                        verbose_name="מי",
                    ),
                ),
                ("body", models.TextField(verbose_name="תוכן")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="matazim.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "הודעה בשיחה",
                "verbose_name_plural": "הודעות בשיחה",
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
