# Generated by Django 5.2.15 on 2026-09-13 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import matazim.storage


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0022_request_recommendation_alter_request_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="מה זה")),
                ("about", models.TextField(blank=True, default="", verbose_name="כמה מילים על זה")),
                (
                    "work_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=matazim.storage.PrivateStorage(),
                        upload_to=matazim.storage.submission_upload_path,
                        verbose_name="קובץ",
                    ),
                ),
                ("link", models.URLField(blank=True, default="", verbose_name="קישור")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "מחכה למוביל/ה"),
                            ("returned", "הוחזר לתיקון"),
                            ("approved", "אושר"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "answers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="matazim.submission",
                        verbose_name="תשובה להגשה",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="matazim.leader",
                        verbose_name="הוגש ל",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="matazim.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "הגשה",
                "verbose_name_plural": "הגשות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(verbose_name="מה נכתב")),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting", "מחכה למוביל/ה"),
                            ("returned", "הוחזר לתיקון"),
                            ("approved", "אושר"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="matazim.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "משוב",
                "verbose_name_plural": "משובים",
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
