# Generated by Django 5.2.15 on 2026-09-13 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0023_submission_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("feedback", "משוב חדש"),
                            ("work_approved", "עבודה אושרה"),
                            ("work_returned", "עבודה הוחזרה"),
                            ("work_waiting", "עבודה מחכה לך"),
                            ("joined", "צירוף למוביל/ה"),
                            ("certified", "הסמכה"),
                        ],
                        max_length=30,
                    ),
                ),
                ("text", models.CharField(max_length=300, verbose_name="מה קרה")),
                ("url", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "התראה",
                "verbose_name_plural": "התראות",
                "ordering": ["-created_at"],
            },
        ),
    ]
