# Generated by Django 5.2.15 on 2026-09-14 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0024_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="מה")),
                ("about", models.TextField(blank=True, default="", verbose_name="פרטים")),
                ("starts_at", models.DateTimeField(db_index=True, verbose_name="מתי")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="עד מתי")),
                (
                    "place",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="איפה"),
                ),
                ("for_everyone", models.BooleanField(default=True, verbose_name="לכל התוכנית")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="להציג בעמוד הפומבי"),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="בוטל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="matazim.studyclass",
                        verbose_name="לכיתות",
                    ),
                ),
                (
                    "leaders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="matazim.leader",
                        verbose_name="למובילים",
                    ),
                ),
                (
                    "program_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="של מנהל/ת התוכנית",
                    ),
                ),
            ],
            options={
                "verbose_name": "יום שיא",
                "verbose_name_plural": "ימי שיא",
                "ordering": ["starts_at"],
            },
        ),
    ]
