# Generated by Django 5.2.15 on 2026-09-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0025_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("feedback", "משוב חדש"),
                    ("work_approved", "עבודה אושרה"),
                    ("work_returned", "עבודה הוחזרה"),
                    ("work_waiting", "עבודה מחכה לך"),
                    ("joined", "צירוף למוביל/ה"),
                    ("certified", "הסמכה"),
                    ("event", "יום שיא"),
                ],
                max_length=30,
            ),
        ),
    ]
