# Generated by Django 5.2.15 on 2026-09-14 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0026_alter_notification_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("announcement", "הודעה מהתוכנית"),
                            ("post", "פוסט"),
                            ("work", "תוצר"),
                        ],
                        db_index=True,
                        default="post",
                        max_length=20,
                    ),
                ),
                ("body", models.TextField(verbose_name="מה לספר")),
                ("hidden_at", models.DateTimeField(blank=True, null=True, verbose_name="הוסתר")),
                (
                    "hidden_reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="למה הוסתר"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="מי כתב",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matazim_community",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="של מנהל/ת התוכנית",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_as",
                        to="matazim.submission",
                        verbose_name="תוצר משותף",
                    ),
                ),
            ],
            options={
                "verbose_name": "פוסט",
                "verbose_name_plural": "קהילה",
                "ordering": ["-created_at"],
            },
        ),
    ]
