# Generated by Django 5.2.15 on 2026-09-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0027_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="מה לימדתם")),
                ("happened_on", models.DateField(db_index=True, verbose_name="מתי")),
                ("minutes", models.PositiveIntegerField(default=45, verbose_name="כמה זמן")),
                ("learners", models.PositiveIntegerField(default=0, verbose_name="כמה תלמידים")),
                (
                    "place",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="איפה"),
                ),
                ("went_well", models.TextField(blank=True, default="", verbose_name="מה עבד")),
                ("was_hard", models.TextField(blank=True, default="", verbose_name="מה היה קשה")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="בוטל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching",
                        to="matazim.student",
                        verbose_name="מט״צ",
                    ),
                ),
            ],
            options={
                "verbose_name": "מפגש הדרכה",
                "verbose_name_plural": "פרקטיקום",
                "ordering": ["-happened_on", "-created_at"],
            },
        ),
    ]
