# Generated by Django 5.2.15 on 2026-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0028_teachingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reminded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="נשלחה תזכורת"),
        ),
    ]
