# Generated by Django 5.2.15 on 2026-09-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0029_event_reminded_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="public_consent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="הסכמת היוצר/ת לפרסום"),
        ),
        migrations.AddField(
            model_name="submission",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="אושר לפרסום"),
        ),
        migrations.AddField(
            model_name="submission",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
