# Generated by Django 5.2.15 on 2026-09-14 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0030_submission_public_consent_at_submission_published_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="שם")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="matazim_institutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="מנהלי/ות התוכנית",
                    ),
                ),
            ],
            options={
                "verbose_name": "מוסד",
                "verbose_name_plural": "מוסדות",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="matazim.institution",
                verbose_name="מוסד",
            ),
        ),
        migrations.AddField(
            model_name="leader",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leaders",
                to="matazim.institution",
                verbose_name="מוסד",
            ),
        ),
        migrations.AddField(
            model_name="leaderinvite",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="matazim.institution",
                verbose_name="מוסד",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="matazim.institution",
                verbose_name="מוסד",
            ),
        ),
    ]
