# Generated by Django 5.2.15 on 2026-09-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0032_fill_institution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="program_manager",
        ),
        migrations.RemoveField(
            model_name="leader",
            name="program_manager",
        ),
        migrations.RemoveField(
            model_name="leaderinvite",
            name="program_manager",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="is_program_manager",
        ),
        migrations.RemoveField(
            model_name="post",
            name="program_manager",
        ),
    ]
