# Generated by Django 5.2.15 on 2026-09-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matazim", "0034_require_institution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=80, unique=True, verbose_name="מזהה ההדרכה")),
                ("is_active", models.BooleanField(default=True, verbose_name="זמינה")),
                ("note", models.TextField(blank=True, default="", verbose_name="למה היא כאן")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "הדרכה זמינה",
                "verbose_name_plural": "הדרכות זמינות",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="LeaderCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=80, verbose_name="מזהה ההדרכה")),
                ("chosen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chosen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf",
                        to="matazim.leader",
                        verbose_name="מוביל/ה",
                    ),
                ),
            ],
            options={
                "verbose_name": "הדרכה שהמוביל/ה הציע/ה",
                "verbose_name_plural": "הדרכות שהמוביל/ה הציע/ה",
                "ordering": ["slug"],
                "unique_together": {("leader", "slug")},
            },
        ),
    ]
