# Generated by Django 5.2.15 on 2026-10-01 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=80)),
                ("decks", models.PositiveSmallIntegerField(default=6)),
                ("dealer_hits_soft_17", models.BooleanField(default=False)),
                ("double_any_two", models.BooleanField(default=True)),
                ("double_after_split", models.BooleanField(default=True)),
                ("max_splits", models.PositiveSmallIntegerField(default=4)),
                ("resplit_aces", models.BooleanField(default=False)),
                ("hit_split_aces", models.BooleanField(default=False)),
                (
                    "surrender",
                    models.CharField(
                        choices=[
                            ("none", "אין כניעה"),
                            ("late", "כניעה מאוחרת"),
                            ("early", "כניעה מוקדמת"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "blackjack_pays",
                    models.CharField(
                        choices=[("3:2", "3:2"), ("6:5", "6:5")], default="3:2", max_length=4
                    ),
                ),
                ("dealer_peeks", models.BooleanField(default=True)),
                ("is_preset", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "decks",
                        "dealer_hits_soft_17",
                        "double_any_two",
                        "double_after_split",
                        "max_splits",
                        "resplit_aces",
                        "hit_split_aces",
                        "surrender",
                        "blackjack_pays",
                        "dealer_peeks",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackjack",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="blackjack.ruleset",
                    ),
                ),
            ],
        ),
    ]
