# Generated by Django 5.2.15 on 2026-10-01 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="blackjack.strategy",
                        help_text="where these cells came from, so a cell can be defended",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule_set",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart",
                        to="blackjack.ruleset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("hard", "קשה"), ("soft", "רך"), ("pair", "זוג")], max_length=4
                    ),
                ),
                (
                    "player",
                    models.PositiveSmallIntegerField(help_text="total, or the rank of a pair"),
                ),
                ("dealer", models.PositiveSmallIntegerField(help_text="2..11, where 11 is an ace")),
                (
                    "action",
                    models.CharField(
                        choices=[("H", "קלף"), ("S", "עצירה"), ("D", "הכפלה"), ("P", "פיצול")],
                        max_length=1,
                    ),
                ),
                (
                    "fallback",
                    models.CharField(
                        choices=[("H", "קלף"), ("S", "עצירה"), ("D", "הכפלה"), ("P", "פיצול")],
                        max_length=1,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="blackjack.chart",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "player", "dealer"],
                "unique_together": {("chart", "kind", "player", "dealer")},
            },
        ),
    ]
