# Generated by Django 5.2.15 on 2026-10-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0002_chart_cell"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cell_kind",
                    models.CharField(
                        choices=[("hard", "קשה"), ("soft", "רך"), ("pair", "זוג")], max_length=4
                    ),
                ),
                ("cell_player", models.PositiveSmallIntegerField()),
                ("cell_dealer", models.PositiveSmallIntegerField()),
                ("player_cards", models.JSONField(blank=True, default=list)),
                (
                    "chosen",
                    models.CharField(
                        choices=[("H", "קלף"), ("S", "עצירה"), ("D", "הכפלה"), ("P", "פיצול")],
                        max_length=1,
                    ),
                ),
                (
                    "correct",
                    models.CharField(
                        choices=[("H", "קלף"), ("S", "עצירה"), ("D", "הכפלה"), ("P", "פיצול")],
                        max_length=1,
                    ),
                ),
                (
                    "correct_fallback",
                    models.CharField(
                        choices=[("H", "קלף"), ("S", "עצירה"), ("D", "הכפלה"), ("P", "פיצול")],
                        max_length=1,
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("answer_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("random", "אקראי"),
                            ("adaptive", "מותאם"),
                            ("simulator", "סימולטור"),
                        ],
                        default="random",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="blackjack.player",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="blackjack.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player", "-created_at"], name="blackjack_a_player__eec9d6_idx"
                    ),
                    models.Index(
                        fields=["player", "cell_kind", "cell_player", "cell_dealer"],
                        name="blackjack_a_player__041390_idx",
                    ),
                ],
            },
        ),
    ]
