# Generated by Django 5.2.15 on 2026-10-01 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0003_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cell_kind",
                    models.CharField(
                        choices=[("hard", "קשה"), ("soft", "רך"), ("pair", "זוג")], max_length=4
                    ),
                ),
                ("cell_player", models.PositiveSmallIntegerField()),
                ("cell_dealer", models.PositiveSmallIntegerField()),
                ("seen", models.PositiveIntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("strength", models.FloatField(default=1.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mastery",
                        to="blackjack.player",
                    ),
                ),
            ],
            options={
                "ordering": ["cell_kind", "cell_player", "cell_dealer"],
                "indexes": [
                    models.Index(fields=["player", "due_at"], name="blackjack_m_player__25ec7e_idx")
                ],
                "unique_together": {("player", "cell_kind", "cell_player", "cell_dealer")},
            },
        ),
    ]
