# Generated by Django 5.2.15 on 2026-10-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0006_coupon_grant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cell_kind",
                    models.CharField(
                        choices=[("hard", "קשה"), ("soft", "רך"), ("pair", "זוג")], max_length=4
                    ),
                ),
                ("cell_player", models.PositiveSmallIntegerField()),
                ("cell_dealer", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tricks",
                        to="blackjack.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("player", "cell_kind", "cell_player", "cell_dealer")},
            },
        ),
    ]
