# Generated by Django 5.2.15 on 2026-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0008_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="show_to_followers",
            field=models.BooleanField(default=True),
        ),
    ]
