# Generated by Django 5.2.15 on 2026-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0009_player_show_to_followers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("youtube_id", models.CharField(max_length=11, unique=True)),
                ("title", models.CharField(help_text="As it is called on YouTube", max_length=200)),
                ("channel", models.CharField(blank=True, max_length=100)),
                (
                    "group",
                    models.CharField(
                        choices=[("game", "איך המשחק עובד"), ("gestures", "איך מסמנים לדילר")],
                        default="game",
                        max_length=10,
                    ),
                ),
                ("seconds", models.PositiveIntegerField(default=0)),
                (
                    "why",
                    models.CharField(
                        help_text="What a person gets from it, in Hebrew", max_length=300
                    ),
                ),
                ("language", models.CharField(default="en", max_length=5)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["group", "order", "pk"],
            },
        ),
    ]
