# Generated by Django 5.2.15 on 2026-10-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0010_clip"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cards", models.JSONField(blank=True, default=list)),
                ("position", models.PositiveIntegerField(default=0)),
                ("cut_at", models.PositiveIntegerField(default=0)),
                ("chips", models.IntegerField(default=1000)),
                ("refills", models.PositiveIntegerField(default=0)),
                ("shuffles", models.PositiveIntegerField(default=0)),
                ("step", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_table",
                        to="blackjack.player",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="blackjack.ruleset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bet", models.PositiveIntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[("insurance", "ביטוח"), ("player", "תורכם"), ("settled", "נסגרה")],
                        default="player",
                        max_length=10,
                    ),
                ),
                ("dealer", models.JSONField(default=list)),
                ("hands", models.JSONField(default=list)),
                ("active", models.PositiveSmallIntegerField(default=0)),
                ("insurance", models.PositiveIntegerField(default=0)),
                ("dealer_natural", models.BooleanField(default=False)),
                (
                    "net",
                    models.IntegerField(
                        default=0, help_text="Chips won or lost, insurance included"
                    ),
                ),
                ("log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="blackjack.ruleset",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="blackjack.playtable",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
